from enum import StrEnum

from .en import DEFAULT_SYSTEM_PROMPT_ROLE as EN_DEFAULT_SYSTEM_PROMPT_ROLE
from .en import REASONING_PATTERNS as EN_REASONING_PATTERNS
from .en import SYSTEM_PROMPT_PHRASES_TO_REMOVE as EN_SYSTEM_PROMPT_PHRASES_TO_REMOVE
from .en import SYSTEM_PROMPT_SECTIONS_TO_REMOVE as EN_SYSTEM_PROMPT_SECTIONS_TO_REMOVE
from .en import SYSTEM_PROMPT_TEMPLATES as EN_SYSTEM_PROMPT_TEMPLATES
from .en import TRIVIAL_VOCABULARY as EN_TRIVIAL_VOCABULARY
from .fr import DEFAULT_SYSTEM_PROMPT_ROLE as FR_DEFAULT_SYSTEM_PROMPT_ROLE
from .fr import PROMPT_PHRASES_TO_REMOVE as FR_SYSTEM_PROMPT_PHRASES_TO_REMOVE
from .fr import PROMPT_SECTIONS_TO_REMOVE as FR_SYSTEM_PROMPT_SECTIONS_TO_REMOVE
from .fr import REASONING_PATTERNS as FR_REASONING_PATTERNS
from .fr import SYSTEM_PROMPT_TEMPLATES as FR_SYSTEM_PROMPT_TEMPLATES
from .fr import TRIVIAL_VOCABULARY as FR_TRIVIAL_VOCABULARY
from .types import SystemPromptTypes


class SystemPromptLangs(StrEnum):
    """All instruction languages."""

    EN = "EN"
    FR = "FR"


SYSTEM_PROMPT_LANGS_LIST = list(map(str, SystemPromptLangs))
DEFAULT_SYSTEM_PROMPT_LANG = SystemPromptLangs.EN

ALL_REASONING_PATTERNS = {
    SystemPromptLangs.EN: EN_REASONING_PATTERNS,
    SystemPromptLangs.FR: FR_REASONING_PATTERNS,
}
ALL_TRIVIAL_VOCABULARY = {
    SystemPromptLangs.EN: EN_TRIVIAL_VOCABULARY,
    SystemPromptLangs.FR: FR_TRIVIAL_VOCABULARY,
}
ALL_DEFAULT_SYSTEM_PROMPT_ROLE = {
    SystemPromptLangs.EN: EN_DEFAULT_SYSTEM_PROMPT_ROLE,
    SystemPromptLangs.FR: FR_DEFAULT_SYSTEM_PROMPT_ROLE,
}
ALL_SYSTEM_PROMPT_TEMPLATES = {
    SystemPromptLangs.EN: EN_SYSTEM_PROMPT_TEMPLATES,
    SystemPromptLangs.FR: FR_SYSTEM_PROMPT_TEMPLATES,
}
ALL_SYSTEM_PROMPT_SECTIONS_TO_REMOVE = {
    SystemPromptLangs.EN: EN_SYSTEM_PROMPT_SECTIONS_TO_REMOVE,
    SystemPromptLangs.FR: FR_SYSTEM_PROMPT_SECTIONS_TO_REMOVE,
}
ALL_SYSTEM_PROMPT_PHRASES_TO_REMOVE = {
    SystemPromptLangs.EN: EN_SYSTEM_PROMPT_PHRASES_TO_REMOVE,
    SystemPromptLangs.FR: FR_SYSTEM_PROMPT_PHRASES_TO_REMOVE,
}

__all__ = (
    "SystemPromptLangs",
    "SystemPromptTypes",
    "SYSTEM_PROMPT_LANGS_LIST",
    "DEFAULT_SYSTEM_PROMPT_LANG",
    "ALL_REASONING_PATTERNS",
    "ALL_TRIVIAL_VOCABULARY",
    "ALL_DEFAULT_SYSTEM_PROMPT_ROLES",
    "ALL_SYSTEM_PROMPT_TEMPLATES",
    "ALL_SYSTEM_PROMPT_SECTIONS_TO_REMOVE",
    "ALL_SYSTEM_PROMPT_PHRASES_TO_REMOVE",
)
