{{- if and .Values.createSecret (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentium.secretName" . }}
  labels:
    {{- include "agentium.labels" . | nindent 4 }}
type: Opaque
stringData:
  AGENTIUM_POSTGRES_PASSWORD: {{ .Values.secret.AGENTIUM_POSTGRES_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.AGENTIUM_POSTGRES_PASSWORD | quote }}
  AGENTIUM_RABBITMQ_PASSWORD: {{ .Values.secret.AGENTIUM_RABBITMQ_PASSWORD | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secret.AGENTIUM_RABBITMQ_PASSWORD | quote }}
  AGENTIUM_MINIO_ROOT_PASSWORD: {{ .Values.secret.AGENTIUM_MINIO_ROOT_PASSWORD | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secret.AGENTIUM_MINIO_ROOT_PASSWORD | quote }}
  OBJECT_STORE_S3_SECRET_KEY: {{ .Values.secret.OBJECT_STORE_S3_SECRET_KEY | quote }}
{{- end }}
