"""E5 proactive recommendations from E1 evaluation signals.

This service is intentionally deterministic. E1.5 already produces rich
signals (question type, failed RAG components, feedback, replays); E5 rolls
them up into Hypervisor Decisions that an operator can accept/reject/apply.
"""
from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Any, Dict, Iterable, List, Optional, Tuple
from uuid import uuid4

from sqlalchemy.orm import Session as DBSession

from app.models.decision import Decision
from app.models.evaluation import EvaluationScore
from app.models.run import Run
from app.services.audit_logger import emit_audit_event
from app.services.evaluation.rag_components import (
    RAG_COMPONENT_LABELS,
    normalize_components,
    normalize_question_type,
    targeted_components,
)


@dataclass
class RecommendationCandidate:
    scope: str
    target_id: Optional[str]
    component: str
    evaluated: int
    breaches: int
    avg_composite: float
    avg_hallucination: float
    question_types: Dict[str, int]
    evidence_run_ids: List[str]

    @property
    def breach_rate(self) -> float:
        return self.breaches / self.evaluated if self.evaluated else 0.0

    @property
    def fingerprint(self) -> str:
        target = self.target_id or "portfolio"
        return f"eval-component:{self.scope}:{target}:{self.component}"


def generate_proactive_recommendations(
    db: DBSession,
    *,
    workspace_id: str,
    since_days: int = 7,
    min_evaluations: int = 3,
    min_breaches: int = 2,
    min_breach_rate: float = 0.5,
    actor: str = "system",
    dry_run: bool = False,
) -> Dict[str, Any]:
    """Create proactive Hypervisor recommendations from recent eval rows.

    Idempotence is enforced by ``rationale.fingerprint``: an existing
    proposed/accepted recommendation for the same component + target is
    returned as skipped instead of duplicated.
    """
    cutoff = datetime.utcnow() - timedelta(days=max(1, int(since_days or 7)))
    rows = (
        db.query(EvaluationScore, Run)
        .outerjoin(Run, EvaluationScore.run_id == Run.id)
        .filter(
            EvaluationScore.workspace_id == workspace_id,
            EvaluationScore.created_at >= cutoff,
        )
        .order_by(EvaluationScore.created_at.desc())
        .limit(2000)
        .all()
    )

    candidates = _build_candidates(
        rows,
        min_evaluations=min_evaluations,
        min_breaches=min_breaches,
        min_breach_rate=min_breach_rate,
    )

    created: List[Decision] = []
    skipped: List[Dict[str, Any]] = []
    previews: List[Dict[str, Any]] = []
    for candidate in candidates:
        payload = _candidate_payload(candidate, since_days=since_days)
        existing = _find_existing(db, workspace_id, candidate.fingerprint)
        if existing:
            skipped.append(
                {
                    "fingerprint": candidate.fingerprint,
                    "decision_id": existing.id,
                    "reason": "already_open",
                }
            )
            continue
        if dry_run:
            previews.append(payload)
            continue
        decision = Decision(
            id=str(uuid4()),
            workspace_id=workspace_id,
            scope=candidate.scope,
            target_id=candidate.target_id,
            kind="recommendation",
            status="proposed",
            title=payload["title"],
            rationale=payload["rationale"],
            impact_estimate=payload["impact_estimate"],
            notes="Generated by E5 proactive recommendation scan.",
        )
        db.add(decision)
        db.flush()
        emit_audit_event(
            workspace_id=workspace_id,
            event_type="recommendation.proactive.generated",
            actor=actor,
            details={
                "decision_id": decision.id,
                "fingerprint": candidate.fingerprint,
                "component": candidate.component,
                "scope": candidate.scope,
                "target_id": candidate.target_id,
                "breach_rate": candidate.breach_rate,
                "breaches": candidate.breaches,
                "evaluated": candidate.evaluated,
            },
            db=db,
        )
        created.append(decision)

    if not dry_run:
        db.commit()

    return {
        "window_days": since_days,
        "evaluations_scanned": len(rows),
        "candidates": len(candidates),
        "created": [_serialize_decision(d) for d in created],
        "skipped": skipped,
        "preview": previews,
    }


def _build_candidates(
    rows: Iterable[Tuple[EvaluationScore, Optional[Run]]],
    *,
    min_evaluations: int,
    min_breaches: int,
    min_breach_rate: float,
) -> List[RecommendationCandidate]:
    buckets: Dict[Tuple[str, Optional[str], str], Dict[str, Any]] = defaultdict(
        lambda: {
            "evaluated": 0,
            "breaches": 0,
            "composite_sum": 0.0,
            "hallucination_sum": 0.0,
            "question_types": defaultdict(int),
            "evidence_run_ids": [],
        }
    )

    for score, run in rows:
        qtype = normalize_question_type(score.question_type)
        failed_components = normalize_components(score.failed_components or [])
        target_components = sorted(set(targeted_components(qtype)) | set(failed_components))
        if not failed_components:
            # Older rows or mild threshold breaches still count toward the
            # denominator for the question-type components.
            failed_components = []
        target_id = run.system_id if run and run.system_id else (score.agent_id or None)
        scope = "system" if target_id else "portfolio"

        for component in target_components:
            bucket = buckets[(scope, target_id, component)]
            bucket["evaluated"] += 1
            bucket["composite_sum"] += float(score.composite_score or 0.0)
            bucket["hallucination_sum"] += float(score.hallucination_rate or 0.0)
            bucket["question_types"][qtype] += 1
            if component in failed_components:
                bucket["breaches"] += 1
                if score.run_id and score.run_id not in bucket["evidence_run_ids"]:
                    bucket["evidence_run_ids"].append(score.run_id)

    candidates: List[RecommendationCandidate] = []
    for (scope, target_id, component), bucket in buckets.items():
        evaluated = int(bucket["evaluated"])
        breaches = int(bucket["breaches"])
        breach_rate = breaches / evaluated if evaluated else 0.0
        if evaluated < min_evaluations:
            continue
        if breaches < min_breaches:
            continue
        if breach_rate < min_breach_rate:
            continue
        candidates.append(
            RecommendationCandidate(
                scope=scope,
                target_id=target_id,
                component=component,
                evaluated=evaluated,
                breaches=breaches,
                avg_composite=round(bucket["composite_sum"] / evaluated, 1),
                avg_hallucination=round(bucket["hallucination_sum"] / evaluated, 3),
                question_types=dict(bucket["question_types"]),
                evidence_run_ids=list(bucket["evidence_run_ids"])[:10],
            )
        )
    candidates.sort(key=lambda c: (c.breach_rate, c.breaches, c.evaluated), reverse=True)
    return candidates[:10]


def _find_existing(db: DBSession, workspace_id: str, fingerprint: str) -> Optional[Decision]:
    rows = (
        db.query(Decision)
        .filter(
            Decision.workspace_id == workspace_id,
            Decision.kind == "recommendation",
            Decision.status.in_(("proposed", "accepted")),
        )
        .order_by(Decision.created_at.desc())
        .limit(200)
        .all()
    )
    for row in rows:
        if (row.rationale or {}).get("fingerprint") == fingerprint:
            return row
    return None


def _candidate_payload(candidate: RecommendationCandidate, *, since_days: int) -> Dict[str, Any]:
    label = RAG_COMPONENT_LABELS.get(candidate.component, candidate.component)
    scope_label = "portfolio" if candidate.scope == "portfolio" else "system"
    proposed_fix = _proposed_fix(candidate.component)
    title = (
        f"{label} breach pattern on {scope_label} "
        f"({candidate.breaches}/{candidate.evaluated} in {since_days}d)"
    )
    rationale = {
        "source": "proactive_eval",
        "fingerprint": candidate.fingerprint,
        "component": candidate.component,
        "component_label": label,
        "window_days": since_days,
        "evaluated": candidate.evaluated,
        "breaches": candidate.breaches,
        "breach_rate": round(candidate.breach_rate, 4),
        "avg_composite": candidate.avg_composite,
        "avg_hallucination": candidate.avg_hallucination,
        "question_types": candidate.question_types,
        "evidence_run_ids": candidate.evidence_run_ids,
        "proposed_fix": proposed_fix,
        "suggestion": proposed_fix["summary"],
    }
    impact_estimate = {
        "quality_risk": round(candidate.breach_rate, 4),
        "affected_runs": candidate.breaches,
        "confidence": min(0.95, 0.45 + candidate.breach_rate / 2),
    }
    return {
        "title": title,
        "rationale": rationale,
        "impact_estimate": impact_estimate,
    }


def _proposed_fix(component: str) -> Dict[str, Any]:
    fixes = {
        "retriever": {
            "summary": "Increase retrieval depth and inspect source coverage for repeated misses.",
            "actions": ["raise top_k to 8", "try hybrid/CHAH retrieval", "review missing KB chunks"],
        },
        "knowledge_base": {
            "summary": "Patch or enrich the knowledge base where breached questions lack support.",
            "actions": ["inspect failed run sources", "add canonical source docs", "regenerate RAGET testset"],
        },
        "generator": {
            "summary": "Tighten generation grounding and lower sampling on breached prompts.",
            "actions": ["add stricter system prompt", "lower temperature", "save canonical answers for policy topics"],
        },
        "rewriter": {
            "summary": "Improve query rewriting for multi-turn or distracting questions.",
            "actions": ["force analytical prompt type", "add conversational examples", "replay with rewritten query"],
        },
        "router": {
            "summary": "Tune routing/intent rules for questions that land in the wrong path.",
            "actions": ["inspect chosen mode", "add routing examples", "prefer retrieval-backed answer path"],
        },
    }
    return fixes.get(
        component,
        {
            "summary": "Inspect the breached runs and apply a replay/canonical-answer remediation.",
            "actions": ["open review queue", "apply active suggestion", "compare replay score"],
        },
    )


def _serialize_decision(decision: Decision) -> Dict[str, Any]:
    return {
        "id": decision.id,
        "scope": decision.scope,
        "target_id": decision.target_id,
        "kind": decision.kind,
        "status": decision.status,
        "title": decision.title,
        "rationale": decision.rationale or {},
        "impact_estimate": decision.impact_estimate or {},
        "created_at": decision.created_at.isoformat() if decision.created_at else None,
    }
