parent=keycloak.v2
import=common/keycloak

# Keep parent PatternFly styles, then apply Agentium branding.
styles=css/styles.css css/agentium.css
stylesCommon=vendor/patternfly-v5/patternfly.min.css vendor/patternfly-v5/patternfly-addons.css

darkMode=true

# Hook class for our CSS scope
kcHtmlClass=login-pf agentium-login
kcLoginClass=pf-v5-c-login__main agentium-login-main
kcLoginMainTitle=pf-v5-c-title pf-m-3xl agentium-login-title
kcButtonPrimaryClass=pf-v5-c-button pf-m-primary agentium-btn-primary
kcInputClass=pf-v5-c-form-control agentium-input
