#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 20 10:24:56 2024

@author: kennethezukwoke
"""

import time
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForSeq2SeqLM, AutoModel
from sentence_transformers import SentenceTransformer, util
from sklearn.metrics.pairwise import cosine_similarity
import language_tool_python

#%% Starter...init

language_tool = language_tool_python.LanguageTool('en-US')
qa_model = pipeline("text2text-generation", model="facebook/bart-large-cnn")
embedding_model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
nli_model = pipeline("text-classification", model="facebook/bart-large-mnli") #to compute factuality

#%%
#-- Does not require source text...
def fluency(text):
    '''
    Fluecy compute the quality of the individual sentences

    Parameters
    text (str): Model generated text

    Returns
    Fluency (flaot): Fluency of the generated text, the higher the better.
    '''
    matches = language_tool.check(text)
    return 1 - len(matches) / len(text.split())

#-- only timing is required...
def latency(start_time, end_time):
    '''
    Latency is the inference computational time

    Parameters
        start_time (time): start time.
        end_time (time): end time.

    Returns (time): final inference time. The lower the better.
    '''
    return end_time - start_time

#-- requires only generated text...
def coherence(generated_text, embedding_model):
    '''
    Coherence measures the formation of a cohesive body of text from the sentences.

    Parameters
        generated_tex (str): model generated text.
        embedding_model (torch model): embedding model

    Returns (float): Coherence
    '''
    sentences = generated_text.split('.')
    embeddings = embedding_model.encode(sentences, convert_to_tensor=True)
    coherence_scores = [cosine_similarity([embeddings[i].cpu().numpy()], [embeddings[i + 1].cpu().numpy()])[0][0]
                        for i in range(len(sentences) - 1)]
    return sum(coherence_scores) / len(coherence_scores)

#-- requires only question and generated text
def relevance(question, generated_text, embedding_model):
    '''
    Relevance measure the factual alignment between anwser and response.

    Parameters
        question (str): input question
        generated_text (str): generated text
        embedding_model (torch model): Embedding model 

    Returns (float): relevance similarity
    '''
    question_embedding = embedding_model.encode(question, convert_to_tensor = True)
    response_embedding = embedding_model.encode(generated_text, convert_to_tensor = True)
    similarity = util.pytorch_cos_sim(question_embedding, response_embedding).item()
    return similarity

#%% Factuality,  Consistency and HHEM require knowledge of source text.
# Imagine if we have no idea of the source response (aka ground-truth)? Coin N-inputs from source document for evaluation.

#--factuality
def factuality(generated_text, source_texts, nli_model):
    nli_scores = []
    for source_text in source_texts:
        result = nli_model(f"{generated_text} entails {source_text}")
        nli_scores.append(result[0]['score'] if result[0]['label'] == 'ENTAILMENT' else 0)
    return max(nli_scores)

#-- Consistency
def consistency(generated_text, source_texts, embedding_model):
    '''
    Consistency measures the factual alignment between the anwer and the context.

    Parameters
    generated_text (str): generated text
    source_texts (str): Source text
    embedding_model (torch model): Embedding model

    Returns
    Consistency (float): Consistency score, higher is better
    '''
    generated_embedding = embedding_model.encode(generated_text, convert_to_tensor=True)
    source_embeddings = embedding_model.encode(source_texts, convert_to_tensor=True)
    similarities = [util.pytorch_cos_sim(generated_embedding, source_embedding) for source_embedding in source_embeddings]
    return max(similarities).item()

#-- HHEM
def HHEM(generated_text, source_texts, nli_model, embedding_model):
    """
    Computes the HHEM (Hallucination Evaluation Metric) for the generated text.
    
    Parameters:
    generated_text (str): The text generated by the model.
    source_texts (list of str): List of source documents to compare against.
    
    Returns:
    hhem_score (float): The hallucination score (lower is better, indicating less hallucination).
    """
    # Compute entailment scores using NLI
    nli_scores = []
    for s_text in source_texts:
        result = nli_model(f"{generated_text} entails {s_text}")
        nli_scores.append(result[0]['score'] if result[0]['label'] == 'ENTAILMENT' else 0)

    mean_nli_score = torch.mean(torch.tensor(nli_scores)).item()
    generated_embedding = embedding_model.encode(generated_text, convert_to_tensor = True)
    source_embeddings = embedding_model.encode(source_texts, convert_to_tensor = True)
    similarities = [util.pytorch_cos_sim(generated_embedding, source_embedding).item() for source_embedding in source_embeddings]
    mean_similarity_score = torch.mean(torch.tensor(similarities)).item()
    
    # HHEM score is the inverse of the mean similarity score weighted by the NLI score
    hhem_score = 1 / (mean_similarity_score * mean_nli_score + 1e-8)  # Adding a small epsilon to avoid division by zero
    return hhem_score

#-- Advanced HHEM
def Advance_HHEM(generated_text, source_texts, question, nli_model, embedding_model):
    """
    Computes the advanced HHEM (Hallucination Evaluation Metric) for the generated text.
    
    Parameters:
    generated_text (str): The text generated by the model.
    source_texts (list of str): List of source documents to compare against.
    question (str): The original question or context for the generated response.
    
    Returns:
    hhem_score (float): The hallucination score (lower is better, indicating less hallucination).
    """
    # Compute entailment scores using NLI
    nli_scores = []
    for source_text in source_texts:
        result = nli_model(sequences = generated_text, candidate_labels = ["entailment", "contradiction", "neutral"],
                           hypothesis_template = "This implies that {}.")
        
        entailment_score = result['scores'][result['labels'].index('entailment')]
        nli_scores.append(entailment_score)
    
    mean_nli_score = torch.mean(torch.tensor(nli_scores)).item()
    generated_embedding = embedding_model.encode(generated_text, convert_to_tensor=True)
    source_embeddings = embedding_model.encode(source_texts, convert_to_tensor=True)
    similarities = [util.pytorch_cos_sim(generated_embedding, source_embedding).item() for source_embedding in source_embeddings]

    mean_similarity_score = torch.mean(torch.tensor(similarities)).item()
    # Extract and validate key facts from the generated text
    facts_validated = 0
    facts_total = 0
    for sentence in generated_text.split('.'):
        if sentence.strip():
            facts_total += 1
            qa_result = qa_model(question = question, context=sentence)
            for source_text in source_texts:
                if qa_result['answer'] in source_text:
                    facts_validated += 1
                    break

    fact_validation_score = facts_validated / facts_total if facts_total > 0 else 0
    hhem_score = 1 / (mean_similarity_score * mean_nli_score * fact_validation_score + 1e-8)  # Adding a small epsilon to avoid division by zero
    return hhem_score


#%% Source and target data

source_texts = ["Source document text 1.", "Source document text 2."]
question = "What is the capital of France?"

#%% compute timing..

start_time = time.time()
generated_text = qa_model(question, return_text = True)[0]['generated_text']
end_time = time.time()

#%% Compute consistency and factuality metrics...

# consistency = consistency(generated_text, source_texts)
# factuality = factuality(generated_text, source_texts)
# hhem = HHEM(generated_text, source_texts, nli_model, embedding_model)
# advhhem = Advance_HHEM(generated_text, source_texts, question)


#%% compute the whole metrics..

fluency = fluency(generated_text)
latency = latency(start_time, end_time)
coherence = coherence(generated_text)
relevance = relevance(question, generated_text)

#%%
print(f"Fluency: {fluency:.2f}")
# print(f"Consistency: {consistency}")
print(f"Latency: {latency:.2f} seconds")
print(f"Coherence: {coherence:.2f}")
print(f"Relevance: {relevance:.2f}")

