version: "3.9"

services:
  db:
    image: postgres:15
    container_name: omnirag-db
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES__USER"]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    env_file:
      - ../.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
