FROM python:3.12-slim

# Install dependencies from private Nexus repository using build secrets
RUN --mount=type=secret,id=nexus_username,env=NEXUS_USERNAME \
    --mount=type=secret,id=nexus_password,env=NEXUS_PASSWORD \
    --mount=type=bind,source=../requirements/fastapi.txt,target=/tmp/requirements.txt,readonly \
    pip install --no-cache-dir \
        --index-url "https://$NEXUS_USERNAME:$NEXUS_PASSWORD@nexus.datategy.net/repository/pypi/simple" \
        -r /tmp/requirements.txt

# create and switch to non-root user
ARG USERNAME=papai
ARG USER_UID=20000907
ARG USER_GID=$USER_UID
RUN groupadd --gid "$USER_GID" "$USERNAME" \
    && useradd --uid "$USER_UID" --gid "$USER_GID" -m "$USERNAME"

WORKDIR /app
COPY --chown=$USERNAME:$USERNAME . .

# Temporary: make vector_store writable before using ffspec
RUN mkdir -p /app/vector_store \
    && chown -R "$USERNAME":"$USERNAME" /app/vector_store

USER $USERNAME

EXPOSE 8000

CMD ["python", "run_fastapi.py"]
