FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# Install dependencies (remember to provide PIP_INDEX_URL as private packages are needed)
ARG PIP_INDEX_URL
RUN --mount=type=bind,source=../requirements/fastapi.txt,target=/tmp/requirements/fastapi.txt,readonly \
    pip install --no-cache-dir \
        --index-url=${PIP_INDEX_URL} \
        -r /tmp/requirements/fastapi.txt

# Create to non-root user for runtime
ARG USERNAME=papai
ARG USER_UID=20000907
ARG USER_GID=$USER_UID
RUN groupadd --gid "$USER_GID" "$USERNAME" \
    && useradd --uid "$USER_UID" --gid "$USER_GID" -m "$USERNAME"

WORKDIR /app

COPY --chown=$USERNAME:$USERNAME . .

# Temporary: make vector_store writable before using ffspec
RUN mkdir -p /app/vector_store \
    && chown -R "$USERNAME":"$USERNAME" /app/vector_store

USER $USERNAME

EXPOSE 8000

CMD ["python", "run_fastapi.py"]
