from .en import REASONING_PATTERNS as EN_REASONING_PATTERNS, REASONING_INSTRUCTIONS as EN_REASONING_INSTRUCTIONS
from .fr import REASONING_PATTERNS as FR_REASONING_PATTERNS, REASONING_INSTRUCTIONS as FR_REASONING_INSTRUCTIONS


ALL_REASONING_PATTERNS = {
    "en": EN_REASONING_PATTERNS,
    "fr": FR_REASONING_PATTERNS
}
ALL_REASONING_INSTRUCTIONS= {
    "en": EN_REASONING_INSTRUCTIONS,
    "fr": FR_REASONING_INSTRUCTIONS
}

__all__ = (
    "ALL_REASONING_PATTERNS",
    "ALL_REASONING_INSTRUCTIONS",
)