from .en import ANALYSIS_STEPS_TO_REMOVE as EN_ANALYSIS_STEPS_TO_REMOVE
from .en import CONTEXT_QUESTION_TO_REMOVE as EN_CONTEXT_QUESTION_TO_REMOVE
from .en import PROMPT_PHRASES_TO_REMOVE as EN_PROMPT_PHRASES_TO_REMOVE
from .en import REASONING_INSTRUCTIONS as EN_REASONING_INSTRUCTIONS
from .en import NAIVE_INSTRUCTION as EN_NAIVE_INSTRUCTION
from .en import REASONING_PATTERNS as EN_REASONING_PATTERNS
from .fr import ANALYSIS_STEPS_TO_REMOVE as FR_ANALYSIS_STEPS_TO_REMOVE
from .fr import CONTEXT_QUESTION_TO_REMOVE as FR_CONTEXT_QUESTION_TO_REMOVE
from .fr import PROMPT_PHRASES_TO_REMOVE as FR_PROMPT_PHRASES_TO_REMOVE
from .fr import REASONING_INSTRUCTIONS as FR_REASONING_INSTRUCTIONS
from .fr import NAIVE_INSTRUCTION as FR_NAIVE_INSTRUCTION
from .fr import REASONING_PATTERNS as FR_REASONING_PATTERNS

ALL_REASONING_PATTERNS = {
    "en": EN_REASONING_PATTERNS,
    "fr": FR_REASONING_PATTERNS,
}
ALL_REASONING_INSTRUCTIONS = {
    "en": EN_REASONING_INSTRUCTIONS,
    "fr": FR_REASONING_INSTRUCTIONS,
}
ALL_NAIVE_INSTRUCTIONS = {
    "en": EN_NAIVE_INSTRUCTION,
    "fr": FR_NAIVE_INSTRUCTION,
}
ALL_ANALYSIS_STEPS_TO_REMOVE = {
    "en": EN_ANALYSIS_STEPS_TO_REMOVE,
    "fr": FR_ANALYSIS_STEPS_TO_REMOVE,
}
ALL_CONTEXT_QUESTION_TO_REMOVE = {
    "en": EN_CONTEXT_QUESTION_TO_REMOVE,
    "fr": FR_CONTEXT_QUESTION_TO_REMOVE,
}
ALL_PROMPT_PHRASES_TO_REMOVE = {
    "en": EN_PROMPT_PHRASES_TO_REMOVE,
    "fr": FR_PROMPT_PHRASES_TO_REMOVE,
}
INSTRUCTION_LANGS = ["en", "fr"]
DEFAULT_INSTRUCTION_LANG = "en"

__all__ = (
    "ALL_REASONING_PATTERNS",
    "ALL_REASONING_INSTRUCTIONS",
    "ALL_ANALYSIS_STEPS_TO_REMOVE",
    "ALL_CONTEXT_QUESTION_TO_REMOVE",
    "ALL_PROMPT_PHRASES_TO_REMOVE",
)
