# -*- coding: utf-8 -*-
"""Align the PIH AI Factory RFI response draft with Annex B v3.

Input is generated by build_pih_rfi_response.py.
Output: docs/pih/RFI-PIH-AI-Factory-Response-v3.docx

This is a surgical commercial alignment pass. It does not alter technical
architecture, RFI section ordering, references, or evaluation content.
"""
import copy
import os

from docx import Document

HERE = os.path.dirname(os.path.abspath(__file__))
PIH = os.path.join(os.path.dirname(HERE), "pih")
SRC = os.path.join(PIH, "RFI-PIH-AI-Factory-Response-DRAFT.docx")
OUT = os.path.join(PIH, "RFI-PIH-AI-Factory-Response-v3.docx")

doc = Document(SRC)


def find(prefix):
    for p in doc.paragraphs:
        if p.text.strip().startswith(prefix):
            return p
    raise SystemExit(f"ANCHOR NOT FOUND: {prefix!r}")


def find_contains(text):
    for p in doc.paragraphs:
        if text in p.text:
            return p
    raise SystemExit(f"ANCHOR NOT FOUND: {text!r}")


def set_text(p, text, bold_lead=None):
    for run in list(p.runs):
        run._r.getparent().remove(run._r)
    if bold_lead:
        run = p.add_run(bold_lead)
        run.bold = True
    p.add_run(text)
    return p


def set_cell(cell, value):
    """Replace table cell text while retaining the cell's existing paragraph style."""
    p = cell.paragraphs[0]
    for run in list(p.runs):
        run._r.getparent().remove(run._r)
    p.add_run(value)
    for extra in cell.paragraphs[1:]:
        extra._p.getparent().remove(extra._p)


def commercial_table():
    for table in doc.tables:
        if table.cell(0, 0).text.strip() == "Component":
            return table
    raise SystemExit("COMMERCIAL TABLE NOT FOUND")


# ---------------------------------------------------------------- §3.2 opening
p = find("Our commercial design has one purpose")
set_text(
    p,
    "Our commercial design has one purpose: PIH's cost per delivered agent falls as the factory "
    "matures, without a per-user licence or a Datategy per-execution consumption charge. SaaS "
    "inference is passed through at cloud tariff without markup. Catalogue unit prices apply to "
    "reuse instances: new agents configured from patterns, skills and connectors already delivered "
    "and validated; their business rules, parameters, rights and acceptance criteria are adapted, "
    "but their technical mechanism is not rebuilt from zero.",
    bold_lead="Commercial principle — ",
)

# ---------------------------------------------------------------- §3.2 table
tbl = commercial_table()
rows = [
    (
        "Agent build — catalogue unit price (reuse instance)",
        "Per accepted agent, by S/M/C complexity tier; all-inclusive front-office unit requested by PIH",
        "Simple ≈ $3.5–5k · Medium ≈ $9–13k · Complex ≈ $20–30k. Tier, systems, "
        "acceptance criteria and reuse/first-of-type status are fixed in the design card before build.",
    ),
    (
        "First-of-type premium",
        "First agent creating or materially extending a pattern, skill or connector",
        "+50% / +50–75% / +75–100% applied to the catalogue price selected in the approved design "
        "card, before volume reduction. Premium is non-degressive and separately identified.",
    ),
    (
        "Volume reduction",
        "Accepted reuse instances only",
        "−10% only on incremental units 101–250; −20% only on incremental units 251+. No "
        "retroactive rebate. First-of-type agents are excluded from the count and reduction.",
    ),
    (
        "Agentium runtime — active programme",
        "Included while an active contracted factory capacity plan is in force",
        "No separate user fee and no Datategy per-execution charge. Runtime provides evaluation, "
        "replay, governance and audit as product capabilities.",
    ),
    (
        "Platform Subscription — post-programme",
        "Annual / capacity tier; commercial tier confirmed at proposal/shortlist",
        "Covers create/modify rights, product updates, security patches, compatibility, golden-set "
        "regression and N3 support after the programme. PIH retains the right to run delivered versions.",
    ),
    (
        "Knowledge capacity (Document Center)",
        "Shared memory scoped by source type and volume; never per agent",
        "Source inventory distinguishes knowledge bases, native pages, scanned/OCR pages, languages, "
        "metadata/cleaning and storage. Allowance and packs are priced at proposal stage.",
    ),
    (
        "AgentOps managed service (§13)",
        "Per accepted live agent per month; operational service is transferable",
        "≈ $50–70 / agent / month, tiered by risk. PIH may operate agents itself or appoint another "
        "operator; this does not transfer Agentium product IP or maintenance/subscription rights.",
    ),
    (
        "T&M day rates (staff augmentation)",
        "Pilot, discovery, change requests or scope outside catalogue unit pricing",
        "AI/Data engineer $149 · Developer $149 · QA/Eval engineer $149 · CoE Director $349 · "
        "Solution Architect $880. Not added to an all-inclusive unit-priced agent. Remote-first; "
        "targeted Doha gates only; travel at cost.",
    ),
    (
        "Sovereign infrastructure",
        "PIH-owned reference specification or managed option",
        "On quote — see §11 for sovereign serving options.",
    ),
]

# Existing commercial table has six data rows. Clone its last formatted row
# enough times to fit the v3 commercial model without creating unstyled rows.
while len(tbl.rows) - 1 < len(rows):
    tbl._tbl.append(copy.deepcopy(tbl.rows[-1]._tr))
for idx, values in enumerate(rows, 1):
    for cell, value in zip(tbl.rows[idx].cells, values):
        set_cell(cell, value)

# ---------------------------------------------------------------- §3.3 inference
p = find_contains("SaaS endpoint costs passed through")
set_text(
    p,
    "SaaS endpoint costs are passed through at cloud tariff without markup; sovereign serving is "
    "priced as a PIH infrastructure envelope. We target a −30–50% reduction in cost per execution "
    "over 12 months through caching, right-sized routing and prompt optimisation, measured against "
    "a jointly agreed baseline and reviewed quarterly. This is a jointly managed optimisation target, "
    "not a guaranteed reduction.",
    bold_lead="Commercial structure & trajectory (Q5A.2) — ",
)

# ---------------------------------------------------------------- §3.4 payment
p = find_contains("we request a mobilisation payment at signature")
set_text(
    p,
    "we request a mobilisation payment at signature covering factory onboarding, internal capacity "
    "reservation and squad ramp-up; the pilot/staff-augmentation phase is invoiced monthly; and "
    "industrial delivery is paid through short monthly or wave milestones rather than a single "
    "deferred 200-agent step.",
    bold_lead="Cash profile — ",
)
# ---------------------------------------------------------------- Pilot remote-first
p = find_contains("mobilisation plan: week 1–2 factory onboarding")
set_text(
    p,
    "mobilisation plan: week 1–2 factory onboarding (access, environments, Abstraction Layer "
    "interfaces, data-quality audit kickoff), delivered remote-first by a solution architect, agentic "
    "tech lead, 3–4 CoE engineers, QA/eval engineer and SAP expertise. Targeted Doha attendance is "
    "reserved for jointly agreed mobilisation, security/UAT or critical go-live gates; weeks 3–13: "
    "build and parallel run; go-live per PIH gates.",
    bold_lead="Mobilisation & team (Q2B.1) — ",
)
p = find_contains("Phase 1 (validation): one concentrated squad")
set_text(
    p,
    "Phase 1 (validation): one concentrated internal Datategy squad — architect, tech lead, 3–4 "
    "engineers and QA/eval — optimised for pattern creation and gate calibration. Phase 2 (volume): "
    "Datategy scales through internal CoE recruitment and allocation of build cells around a stable "
    "architecture core; pattern authoring shifts to instantiation, so the senior-to-engineer ratio "
    "drops. Phase 3 (cognitive agents): research-grade evaluation, RCA and multi-step-reasoning "
    "profiles join the core while build cells maintain volume.",
    bold_lead="Team evolution across phases (Q2C.1) — ",
)

# ---------------------------------------------------------------- §5 Factory economics
p = find("Reuse is our grammar, not a slogan.")
set_text(
    p,
    "A reuse instance is a new agent configured from validated patterns, skills and connectors: its "
    "business rules, parameters, rights and acceptance criteria change, but its technical mechanism "
    "is not rebuilt from zero. A first-of-type is the first agent creating or materially extending "
    "one of those reusable assets. Every agent is authored from typed, versioned components: Skills "
    "(atomic capabilities), Capabilities (business promises), Systems (assembled agents) and Patterns "
    "(structural templates).",
    bold_lead="Reuse is our grammar, not a slogan. ",
)
p = find_contains("we accept the 30% (pattern reuse)")
set_text(
    p,
    "we propose a 30% pattern-reuse / 15% component-standardisation measurement method, subject to "
    "PIH clarification of the applicable baseline, calculation and contractual status. Proposed "
    "baseline: first-of-type build cost per pattern; reporting: monthly factory ledger; prerequisites: "
    "stable pattern taxonomy and PIH data/environment access.",
    bold_lead="Measurement method (Q2A.1) — ",
)
p = find_contains("Phase 1 is dominated by first-of-type patterns")
set_text(
    p,
    "Phase 1 is dominated by first-of-type patterns, skills and connectors, whose premium is scoped "
    "in the design card. Phase 2 transitions to majority reuse instances, eligible for the incremental "
    "volume reduction only after production acceptance. Phase 3 cognitive agents reuse the evaluated "
    "component base while applying the appropriate Complex-tier governance. Primary drivers are pattern "
    "coverage, connector catalogue completeness, golden-set maturity and AI-assisted authoring.",
    bold_lead="Cost trajectory (Q2A.2) — ",
)

# ---------------------------------------------------------------- §13 AgentOps
p = find("We can deliver AgentOps as build-partner")
set_text(
    p,
    "We can deliver AgentOps as build-partner or hand operating responsibility to PIH or an operator "
    "of PIH's choice; telemetry, runbooks and delivered-agent evidence are handover-ready. Operational "
    "handover does not transfer Agentium product IP or the post-programme rights required for updates, "
    "compatibility, golden-set regression and N3 support.",
)

# ---------------------------------------------------------------- Named individuals: autonomous delivery wording
for table in doc.tables:
    for row in table.rows:
        if row.cells and row.cells[0].text.strip().startswith("SAP module experts"):
            set_cell(row.cells[1], "‹ TO COMPLETE — Datategy nominated SAP module experts ›")
            set_cell(row.cells[2], "Process credentials per module; internal Datategy staffing plan "
                                   "confirmed at shortlist.")
        for cell in row.cells:
            if "delivery partnership" in cell.text.lower():
                set_cell(cell, "Agentic + integration engineering proven on SAP-adjacent estates "
                               "(SuccessFactors, ERP triggers). Named Datategy SAP module experts "
                               "confirmed at shortlist.")

for p in doc.paragraphs:
    if "to be nominated with delivery partner" in p.text.lower():
        set_text(p, "‹ TO COMPLETE — named Datategy SAP module experts (FI, MM, SD, HCM, FI-AA) "
                    "with process credentials; CVs at shortlist stage ›")
    if "capability our delivery partnership brings" in p.text.lower():
        set_text(
            p,
            "Acknowledged gap per the RFI's reference criteria: our direct references do not include "
            "an SAP financial-posting agent delivery. Named Datategy SAP module experts and relevant "
            "financial-posting evidence will be presented at shortlist stage.",
        )

# Keep the document's draft status, but make the generated revision visible.
for section in doc.sections:
    for p in section.header.paragraphs:
        if "DRAFT — internal work in progress" in p.text:
            for run in p.runs:
                if "DRAFT — internal work in progress" in run.text:
                    run.text = run.text.replace(
                        "DRAFT — internal work in progress",
                        "DRAFT v3 — internal work in progress",
                    )
for p in doc.paragraphs:
    for run in p.runs:
        if "DRAFT v1 — internal" in run.text:
            run.text = run.text.replace("DRAFT v1 — internal", "DRAFT v3 — internal")

doc.save(OUT)

# ---------------------------------------------------------------- verification
out = Document(OUT)
text = "\n".join(p.text for p in out.paragraphs)
checks = {
    "old consumption wording removed": "no consumption tax" not in text,
    "reuse definition present": "A reuse instance is a new agent" in text,
    "subscription present": "Platform Subscription" in "\n".join(
        cell.text for table in out.tables for row in table.rows for cell in row.cells
    ),
    "conditional reuse method": "subject to PIH clarification" in text,
    "remote-first pilot": "remote-first" in text,
    "old partner wording removed": "delivery partner" not in text,
}
for name, passed in checks.items():
    print(("OK" if passed else "FAIL"), name)
print("saved:", OUT)
