"""Seed catalog of canonical Skills + universal Capabilities.

Each entry in `SEED_SKILLS` is a wrapper around an existing OmniRAG
endpoint. The actual `invoke()` callable is registered in
`backend/app/services/skills_registry/wrappers.py`; here we only declare
the typed contracts so the registry is queryable from `/skills` without
the runtime needing to be alive.
"""
from datetime import datetime
from typing import Any, Dict, List

from sqlalchemy.orm import Session as DBSession

from app.models.capability import Capability
from app.models.skill import Skill


RETRIEVAL_POLICY_PROPERTIES: Dict[str, Any] = {
    "top_k": {"type": "integer", "default": 5},
    "candidate_pool_k": {"type": "integer"},
    "synthesis_k": {"type": "integer"},
    "source_display_k": {"type": "integer"},
    "rag_pipeline_mode": {"type": "string", "enum": ["auto", "vector", "dense", "hybrid", "hah", "chah"]},
    "latency_profile": {"type": "string", "enum": ["fast", "balanced", "deep"]},
    "retrieval_profile": {"type": "string", "enum": ["oracle_fast", "chat", "deep_async"]},
    "deep_retrieval": {"type": "boolean"},
    "knowledge_scope": {"type": "string"},
    "collection": {"type": "string"},
    "collection_name": {"type": "string"},
    "context_collection": {"type": "string"},
    "retrieval_filters": {"type": "object"},
}


def _translation_skill(
    slug: str,
    name: str,
    description: str,
    skill_type: str,
    *,
    mode: str = "async",
    timeout_ms: int = 1_800_000,
    required: List[str] | None = None,
    properties: Dict[str, Any] | None = None,
    outputs: Dict[str, Any] | None = None,
) -> Dict[str, Any]:
    return {
        "slug": slug,
        "version": "1",
        "name": name,
        "description": description,
        "type": skill_type,
        "provider": "internal",
        "certification_level": "enterprise",
        "execution": {"mode": mode, "timeout_ms": timeout_ms, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_batch_stage", "unit_price": 0.0, "currency": "EUR"},
        "input_schema": {
            "type": "object",
            "required": required or [],
            "properties": {
                "batch_id": {"type": "string"},
                "agent_identity": {"type": "string"},
                "tenant_policy": {"type": "object"},
                **(properties or {}),
            },
        },
        "output_schema": {
            "type": "object",
            "properties": {
                "status": {"type": "string"},
                "verdict": {"type": "string"},
                "showcase_seed": {"type": "boolean"},
                **(outputs or {}),
            },
        },
    }


TRANSLATION_SKILLS: List[Dict[str, Any]] = [
    _translation_skill(
        "translation_archive_ingest_v1",
        "Translation Archive Ingest",
        "Validates a tenant-scoped DITA source archive, manifest hash and topic inventory.",
        "translation_ingestion",
        required=["archive_ref", "manifest_sha256"],
        properties={
            "archive_ref": {"type": "string"},
            "manifest_sha256": {"type": "string"},
            "source_lang": {"type": "string", "default": "fr-FR"},
            "target_langs": {"type": "array", "items": {"type": "string"}},
        },
        outputs={
            "parsed_topics": {"type": "integer"},
            "archive_hash": {"type": "string"},
            "glossary_refs": {"type": "array"},
        },
    ),
    _translation_skill(
        "translation_memory_retrieve_v1",
        "Translation Memory Retrieve",
        "Retrieves bilingual examples from sovereign FAISS/BGE-M3 translation memory.",
        "retrieval",
        timeout_ms=600_000,
        properties={
            "source_segments": {"type": "array"},
            "kb_dir": {"type": "string"},
            "k_retrieval": {"type": "integer", "default": 2},
            "embedding_model": {"type": "string", "default": "BAAI/bge-m3"},
        },
        outputs={
            "examples": {"type": "array"},
            "index_versions": {"type": "array"},
            "cache_hit_rate": {"type": "number"},
        },
    ),
    _translation_skill(
        "translation_label_index_resolve_v1",
        "Translation Label Index Resolve",
        "Resolves REFERENT, INDEX and TEXTES-LOCA-GAMA values while preserving protected DITA placeholders.",
        "transformation",
        timeout_ms=600_000,
        properties={
            "library_ref_path": {"type": "string"},
            "preserve_conkeyref_byte_equal": {"type": "boolean", "default": True},
        },
        outputs={
            "labels_resolved": {"type": "integer"},
            "protected_placeholders": {"type": "integer"},
        },
    ),
    _translation_skill(
        "translation_pivot_normalize_v1",
        "Translation F1 Pivot Normalize",
        "Normalizes fr-FR DITA content into an en-GB pivot with deterministic local model routing.",
        "generation",
        properties={
            "source_lang": {"type": "string", "default": "fr-FR"},
            "pivot_lang": {"type": "string", "default": "en-GB"},
            "model": {"type": "string", "default": "sovereign-vllm:unsloth/gpt-oss-20b-BF16"},
            "temperature": {"type": "number", "default": 0},
        },
        outputs={
            "pivot_lang": {"type": "string"},
            "segments": {"type": "integer"},
            "token_usage": {"type": "object"},
        },
    ),
    _translation_skill(
        "translation_fanout_v1",
        "Translation F2 Fan-out",
        "Fans out the pivot into all target locales with bounded parallelism and replayable topic state.",
        "batch",
        properties={
            "target_langs": {"type": "array", "items": {"type": "string"}},
            "num_parallel_topics": {"type": "integer", "default": 5},
            "gpu_ids": {"type": "array", "items": {"type": "integer"}},
        },
        outputs={
            "target_langs": {"type": "integer"},
            "completed_topics": {"type": "integer"},
            "state_checkpoint_ref": {"type": "string"},
        },
    ),
    _translation_skill(
        "translation_j2450_qa_v1",
        "Translation J2450 QA",
        "Runs seven SAE J2450 QA agent identities and supervisor convergence.",
        "analysis",
        properties={
            "limit_qa_loop": {"type": "integer", "default": 5},
            "categories": {"type": "array", "items": {"type": "string"}},
            "severity_policy": {"type": "string", "default": "no_error"},
        },
        outputs={
            "agents": {"type": "array"},
            "weighted_score": {"type": "number"},
            "loop_count": {"type": "integer"},
        },
    ),
    _translation_skill(
        "translation_post_guard_v1",
        "Translation Post Guard",
        "Applies deterministic XML, DITA placeholder, RTL and LLM-artifact guardrails before delivery.",
        "compliance",
        timeout_ms=900_000,
        properties={
            "blocking_modes": {"type": "array", "items": {"type": "string"}},
            "cdc_e1_strict": {"type": "boolean", "default": True},
        },
        outputs={
            "cdc_e1_violations": {"type": "integer"},
            "blocked_topic": {"type": "string"},
            "guard_report_ref": {"type": "string"},
        },
    ),
    _translation_skill(
        "translation_cdt_gate_v1",
        "Translation CDT Gate",
        "Freezes, approves, rejects or resubmits delivery manifests under human review policy.",
        "human_augmented",
        mode="sync",
        timeout_ms=300_000,
        properties={
            "action": {"type": "string"},
            "reviewer_role": {"type": "string", "default": "translation_reviewer"},
            "max_replays_per_topic": {"type": "integer", "default": 3},
        },
        outputs={
            "approval": {"type": "string"},
            "replayed_topics": {"type": "integer"},
            "decision_id": {"type": "string"},
        },
    ),
    _translation_skill(
        "translation_package_delivery_v1",
        "Translation Package Delivery",
        "Packages DITA outputs, reports, SHA256 manifests and simulated SFTP delivery evidence.",
        "delivery",
        timeout_ms=900_000,
        properties={
            "delivery_channel": {"type": "string", "default": "simulated_sftp"},
            "push_requires_human_approval": {"type": "boolean", "default": True},
        },
        outputs={
            "delivery_package": {"type": "string"},
            "receipt": {"type": "string"},
            "manifest_ref": {"type": "string"},
        },
    ),
]


# ---- Skills ----------------------------------------------------------------
# (slug, version, name, description, type, provider, certification, execution,
#  pricing, input_schema, output_schema)
SEED_SKILLS: List[Dict[str, Any]] = [
    *TRANSLATION_SKILLS,
    {
        "slug": "llm_rag_answer_v1",
        "version": "1",
        "name": "RAG Answer",
        "description": "Retrieval-augmented answer with citations. When a 'context' array is supplied (e.g. join.retrieval.results) it synthesises grounded FROM those chunks without a second retrieval; otherwise it runs the orchestrator retrieval (tenant slug resolved).",
        "type": "rag",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "stream", "timeout_ms": 60_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_call", "unit_price": 0.012, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
            "context_id": {"type": "string"},
            "context": {"type": "array", "description": "Pre-retrieved chunks (e.g. join.retrieval.results). When present, the answer is synthesised FROM these (no second retrieval)."},
            "answer_profile": {"type": "string"},
            "lang_target": {"type": "string"},
            **RETRIEVAL_POLICY_PROPERTIES,
        }},
        "output_schema": {"type": "object", "properties": {
            "answer": {"type": "string"},
            "citations": {"type": "array"},
            "decision_steps": {"type": "array"},
        }},
    },
    {
        "slug": "semantic_search_v1",
        "version": "1",
        "name": "Semantic Search",
        "description": "Budget-aware sparse+dense search over the knowledge base.",
        "type": "retrieval",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 8_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.0008, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
            "mode": {"type": "string"},
            "rag_pipeline_mode": {"type": "string"},
            **RETRIEVAL_POLICY_PROPERTIES,
        }},
        "output_schema": {"type": "object", "properties": {
            "results": {"type": "array"},
        }},
    },
    {
        "slug": "multi_hop_retrieve_v1",
        "version": "1",
        "name": "Multi-Hop Retrieve",
        "description": "Decomposed multi-hop retrieval: runs N semantic_search_v1 passes in parallel over the planner's sub_queries (plus the main query) and merges/dedupes the hits (RRF, reusing comparative_retrieval) into the same results[] shape as semantic_search. Used as the retrieval lane for comparison/multi-hop/transversal queries; degrades to a single search when no sub-queries are provided.",
        "type": "retrieval",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 20_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.0016, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
            "sub_queries": {"type": "array", "items": {"type": "string"}},
            "rag_pipeline_mode": {"type": "string"},
            **RETRIEVAL_POLICY_PROPERTIES,
        }},
        "output_schema": {"type": "object", "properties": {
            "results": {"type": "array"},
            "raw_chunks_retrieved": {"type": "integer"},
            "sub_queries": {"type": "array", "items": {"type": "string"}},
            "hop_count": {"type": "integer"},
        }},
    },
    {
        "slug": "chat_trivial_bypass_v1",
        "version": "1",
        "name": "Chat Trivial Bypass",
        "description": "Conservative local bypass for greetings, thanks and acknowledgements before retrieval.",
        "type": "policy",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 500, "retryable": False, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.0, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "bypassed": {"type": "boolean"},
            "answer": {"type": "string"},
            "reason": {"type": "string"},
        }},
    },
    {
        "slug": "chat_grounding_policy_v1",
        "version": "1",
        "name": "Chat Grounding Policy",
        "description": "Resolves workspace/profile grounding instructions before generation.",
        "type": "policy",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 1000, "retryable": False, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.0, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
            "assistant_profile": {"type": "string"},
            "grounding_mode": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "mode": {"type": "string"},
            "require_sources": {"type": "boolean"},
            "fallback_disclaimer": {"type": "string"},
        }},
    },
    {
        "slug": "chat_action_resolver_v1",
        "version": "1",
        "name": "Chat Action Resolver",
        "description": "Matches chat text to workspace action manifests without executing side effects automatically.",
        "type": "tool",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 1500, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.0, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
            "assistant_profile": {"type": "string"},
            "surface": {"type": "string", "default": "chat"},
        }},
        "output_schema": {"type": "object", "properties": {
            "matched": {"type": "boolean"},
            "action_id": {"type": "string"},
            "requires_confirmation": {"type": "boolean"},
        }},
    },
    {
        "slug": "document_ingestion_v1",
        "version": "1",
        "name": "Document Ingestion",
        "description": "Parse and embed a document into the knowledge base.",
        "type": "ingestion",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "async", "timeout_ms": 120_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_doc", "unit_price": 0.04, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["filename"], "properties": {
            "filename": {"type": "string"},
            "collection": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "doc_id": {"type": "string"},
            "chunks": {"type": "integer"},
        }},
    },
    {
        "slug": "eval_radar_v1",
        "version": "1",
        "name": "Evaluation Radar",
        "description": "Multi-axis evaluation (groundedness, relevance, recall, latency, safety).",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 30_000, "retryable": False, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["answer"], "properties": {
            "answer": {"type": "string"},
            "ground_truth": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "axes": {"type": "object"},
            "overall": {"type": "number"},
        }},
    },
    {
        "slug": "claim_audit_v1",
        "version": "1",
        "name": "Claim Audit",
        "description": "Verifies factual claims in an answer against the citations.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 30_000, "retryable": False, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.025, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["answer"], "properties": {
            "answer": {"type": "string"},
            "citations": {"type": "array"},
        }},
        "output_schema": {"type": "object", "properties": {
            "claims": {"type": "array"},
            "verdict": {"type": "string"},
        }},
    },
    {
        "slug": "chat_agentic_plan_v1",
        "version": "1",
        "name": "Chat Agentic Plan",
        "description": "Provider-neutral agentic planner: classifies the request (answer/clarify/reject_oos), picks the reasoning depth and exposes the per-lane retrieval budgets (top_k/synthesis_k/candidate_pool_k, matching the classic chat budget policy) consumed by the retrieve nodes. Clarify is gated (rejected when a project code/identifier is present or the request is not genuinely ambiguous). reject_oos is gated: demoted to answer when a known project/machine/system is named (never rejected on language). Inventory/transversal multi-project questions are forced to the deep lane. Emits sub_queries (2-4 decomposed sub-questions) for comparison/multi-hop/transversal profiles (empty otherwise) to drive the multi_hop_retrieve lane. Schema-placeholder scope hints are dropped. Model resolved via ModelRouter.",
        "type": "planning",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 30_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.004, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
            "conversation_history": {"type": "array"},
            "model": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "action": {"type": "string", "enum": ["answer", "clarify", "reject_oos"]},
            "mode": {"type": "string", "enum": ["fast", "balanced", "deep"]},
            "answer_profile": {"type": "string"},
            "scope_hint": {"type": "string"},
            "clarifying_question": {"type": "string"},
            "oos_reason": {"type": "string"},
            "lang_target": {"type": "string"},
            "confidence": {"type": "number"},
            "retrieval": {"type": "object", "properties": {
                "latency_profile": {"type": "string", "enum": ["fast", "balanced", "deep"]},
                "retrieval_profile": {"type": "string", "enum": ["oracle_fast", "chat", "deep_async"]},
                "top_k": {"type": "integer"},
                "synthesis_k": {"type": "integer"},
                "candidate_pool_k": {"type": "integer"},
                "rag_pipeline_mode": {"type": "string", "enum": ["chah", "auto"]},
                "deep_retrieval": {"type": "boolean"},
            }},
            "sub_queries": {"type": "array", "items": {"type": "string"}},
        }},
    },
    {
        "slug": "chat_self_correct_v1",
        "version": "1",
        "name": "Chat Self Correct",
        "description": "Provider-neutral bounded self-correction reactor (1 pass): picks one repair action. escalate_deep RE-RETRIEVES (deep lane) and re-grounds the answer on the new context, or abstains — never fabricates; translate/declare_partial only transform the already-grounded draft. Model resolved via ModelRouter.",
        "type": "generation",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 45_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_call", "unit_price": 0.012, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["draft_answer"], "properties": {
            "draft_answer": {"type": "string"},
            "query": {"type": "string"},
            "citations": {"type": "array"},
            "composite": {"type": "number"},
            "hallucination_rate": {"type": "number"},
            "mode": {"type": "string"},
            "scope_hint": {"type": "string"},
            "lang_target": {"type": "string"},
            "answer_profile": {"type": "string"},
            "model": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "answer": {"type": "string"},
            "citations": {"type": "array"},
            "action_taken": {"type": "string", "enum": ["escalate_deep", "translate", "declare_partial"]},
        }},
    },
    {
        "slug": "response_eval_v1",
        "version": "1",
        "name": "Response Eval",
        "description": "Embedding-based RAG quality wrapper around ResponseEvaluator. Single authoritative source of the 0-100 composite (ResponseEvaluator score x100), with hallucination_rate, context_count and HHEM/factuality/coherence.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 30_000, "retryable": False, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.002, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["answer"], "properties": {
            "answer": {"type": "string"},
            "citations": {"type": "array"},
            "context_chunks": {"type": "array"},
            "query": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "composite": {"type": "number"},
            "hallucination_rate": {"type": "number"},
            "context_count": {"type": "integer"},
            "hhem": {"type": "number"},
            "factuality": {"type": "number"},
            "coherence": {"type": "number"},
        }},
    },
    {
        "slug": "intelligence_batch_v1",
        "version": "1",
        "name": "Intelligence Batch",
        "description": "Pulls feeds, deduplicates, scores and stores articles for a campaign.",
        "type": "ingestion",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "async", "timeout_ms": 600_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_batch", "unit_price": 0.5, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "feed_ids": {"type": "array"},
        }},
        "output_schema": {"type": "object", "properties": {
            "ingested": {"type": "integer"},
            "errors": {"type": "integer"},
        }},
    },
    {
        "slug": "ministerial_briefing_v1",
        "version": "1",
        "name": "Ministerial Briefing",
        "description": "Builds a sourced daily executive briefing from workspace signals, agenda, projects and open intelligence.",
        "type": "planning",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 12_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_brief", "unit_price": 0.08, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "workspace_name": {"type": "string"},
            "date": {"type": "string"},
            "include_sources": {"type": "boolean", "default": True},
        }},
        "output_schema": {"type": "object", "properties": {
            "briefing": {"type": "object"},
            "sources": {"type": "array"},
        }},
    },
    {
        "slug": "news_signal_synthesis_v1",
        "version": "1",
        "name": "News Signal Synthesis",
        "description": "Summarizes RSS/open-intelligence signals into risks, confidence, source trails and advisory actions.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 10_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_signal_batch", "unit_price": 0.06, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "signals": {"type": "array"},
            "target": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "summary": {"type": "string"},
            "signals": {"type": "array"},
            "sources": {"type": "array"},
        }},
    },
    {
        "slug": "project_risk_explainer_v1",
        "version": "1",
        "name": "Project Risk Explainer",
        "description": "Explains strategic project delay, likely causes, risk and human-validated action options.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 10_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_project", "unit_price": 0.05, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "project_id": {"type": "string"},
            "question": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "project": {"type": "object"},
            "explanation": {"type": "object"},
            "sources": {"type": "array"},
        }},
    },
    {
        "slug": "territorial_signal_map_v1",
        "version": "1",
        "name": "Territorial Signal Map",
        "description": "Produces an illustrative decision map with zones, source-backed signals and non-military recommendations.",
        "type": "visualization",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 10_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_map", "unit_price": 0.07, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "question": {"type": "string"},
            "scope": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "map": {"type": "object"},
            "zones": {"type": "array"},
            "sources": {"type": "array"},
        }},
    },
    {
        "slug": "instruction_draft_v1",
        "version": "1",
        "name": "Instruction Draft",
        "description": "Drafts advisory cabinet instructions from sourced project or territorial signals; never sends externally.",
        "type": "generation",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 10_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_draft", "unit_price": 0.04, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["target_id"], "properties": {
            "target_id": {"type": "string"},
            "target_type": {"type": "string"},
            "instruction_type": {"type": "string"},
            "tone": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "status": {"type": "string"},
            "requires_validation": {"type": "boolean"},
            "body": {"type": "string"},
            "sources": {"type": "array"},
        }},
    },
    {
        "slug": "calendar_read_v1",
        "version": "1",
        "name": "Calendar Read",
        "description": "Reads workspace calendar events and daily summaries from the institutional agenda connector.",
        "type": "connector",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_read", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"date": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"events": {"type": "array"}, "summary": {"type": "string"}}},
    },
    {
        "slug": "calendar_create_event_v1",
        "version": "1",
        "name": "Calendar Create Event",
        "description": "Creates an event in the workspace institutional calendar according to the workspace write policy.",
        "type": "connector",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": False, "idempotent": False},
        "pricing": {"unit": "per_event", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["title", "start_at"], "properties": {"title": {"type": "string"}, "start_at": {"type": "string"}, "end_at": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"event": {"type": "object"}, "requires_validation": {"type": "boolean"}}},
    },
    {
        "slug": "calendar_update_event_v1",
        "version": "1",
        "name": "Calendar Update Event",
        "description": "Updates an event in the workspace institutional calendar.",
        "type": "connector",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": False, "idempotent": False},
        "pricing": {"unit": "per_event", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["event_id"], "properties": {"event_id": {"type": "string"}, "start_at": {"type": "string"}, "title": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"event": {"type": "object"}, "requires_validation": {"type": "boolean"}}},
    },
    {
        "slug": "calendar_cancel_event_v1",
        "version": "1",
        "name": "Calendar Cancel Event",
        "description": "Cancels an event in the workspace institutional calendar.",
        "type": "connector",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": False, "idempotent": False},
        "pricing": {"unit": "per_event", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["event_id"], "properties": {"event_id": {"type": "string"}, "reason": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"event": {"type": "object"}, "requires_validation": {"type": "boolean"}}},
    },
    {
        "slug": "calendar_daily_summary_v1",
        "version": "1",
        "name": "Calendar Daily Summary",
        "description": "Builds a daily institutional agenda summary with conflicts, next event and free slots.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_summary", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"date": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"summary": {"type": "string"}, "events": {"type": "array"}}},
    },
    {
        "slug": "action_plan_create_v1",
        "version": "1",
        "name": "Action Plan Create",
        "description": "Creates a workspace-scoped action item linked to a decision, run, calendar event or source signal.",
        "type": "workflow",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": False, "idempotent": False},
        "pricing": {"unit": "per_action", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["title"], "properties": {"title": {"type": "string"}, "due_at": {"type": "string"}, "priority": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"item": {"type": "object"}, "requires_validation": {"type": "boolean"}}},
    },
    {
        "slug": "action_plan_reschedule_v1",
        "version": "1",
        "name": "Action Plan Reschedule",
        "description": "Reschedules a workspace action item while preserving auditability.",
        "type": "workflow",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": False, "idempotent": False},
        "pricing": {"unit": "per_action", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["item_id", "due_at"], "properties": {"item_id": {"type": "string"}, "due_at": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"item": {"type": "object"}}},
    },
    {
        "slug": "action_plan_status_v1",
        "version": "1",
        "name": "Action Plan Status",
        "description": "Lists and summarizes workspace action items for a cabinet or operator view.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_read", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"status": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"items": {"type": "array"}, "summary": {"type": "object"}}},
    },
    {
        "slug": "action_plan_cancel_v1",
        "version": "1",
        "name": "Action Plan Cancel",
        "description": "Cancels a workspace action item under the workspace write policy.",
        "type": "workflow",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": False, "idempotent": False},
        "pricing": {"unit": "per_action", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["item_id"], "properties": {"item_id": {"type": "string"}, "reason": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"item": {"type": "object"}}},
    },
    {
        "slug": "scenario_generate_v1",
        "version": "1",
        "name": "Scenario Generate",
        "description": "Generates advisory decision scenarios with cost, impact, confidence and risk-reduction scoring.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_scenario_pack", "unit_price": 0.03, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"target_kind": {"type": "string"}, "target_id": {"type": "string"}, "risk_level": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"options": {"type": "array"}}},
    },
    {
        "slug": "scenario_compare_v1",
        "version": "1",
        "name": "Scenario Compare",
        "description": "Compares advisory scenarios and exposes tradeoffs for human decision makers.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_comparison", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"options": {"type": "array"}}},
        "output_schema": {"type": "object", "properties": {"best": {"type": "object"}, "tradeoffs": {"type": "array"}}},
    },
    {
        "slug": "scenario_recommend_v1",
        "version": "1",
        "name": "Scenario Recommend",
        "description": "Selects the recommended scenario while preserving alternatives and reasoning.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_recommendation", "unit_price": 0.03, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"target_kind": {"type": "string"}, "target_id": {"type": "string"}, "risk_level": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"recommended": {"type": "object"}, "options": {"type": "array"}}},
    },
    {
        "slug": "map_layer_read_v1",
        "version": "1",
        "name": "Map Layer Read",
        "description": "Reads workspace map layers, zones and source metadata.",
        "type": "connector",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_read", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"map_slug": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"map": {"type": "object"}, "zones": {"type": "array"}}},
    },
    {
        "slug": "map_zone_score_v1",
        "version": "1",
        "name": "Map Zone Score",
        "description": "Scores map zones using configured signals, projects and source confidence.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 10_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_map", "unit_price": 0.04, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"map_slug": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"scores": {"type": "array"}, "job": {"type": "object"}}},
    },
    {
        "slug": "map_signal_attach_v1",
        "version": "1",
        "name": "Map Signal Attach",
        "description": "Attaches a source signal to a workspace map zone for later scoring.",
        "type": "workflow",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": False, "idempotent": False},
        "pricing": {"unit": "per_signal", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["zone_key", "title"], "properties": {"zone_key": {"type": "string"}, "title": {"type": "string"}, "weight": {"type": "number"}}},
        "output_schema": {"type": "object", "properties": {"signal": {"type": "object"}}},
    },
    {
        "slug": "map_recommendation_generate_v1",
        "version": "1",
        "name": "Map Recommendation Generate",
        "description": "Builds non-military preventive action recommendations from scored map zones.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_recommendation_pack", "unit_price": 0.03, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"map_slug": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"recommendations": {"type": "array"}}},
    },
    {
        "slug": "map_command_apply_v1",
        "version": "1",
        "name": "Map Command Apply",
        "description": "Produces provider-neutral camera, layer and annotation commands for a workspace map renderer.",
        "type": "workflow",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_command", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {
            "type": "object",
            "required": ["intent"],
            "properties": {
                "map_slug": {"type": "string"},
                "intent": {"type": "string"},
                "target": {"type": "string"},
                "layers": {"type": "array", "items": {"type": "string"}},
            },
        },
        "output_schema": {"type": "object", "properties": {"map_state": {"type": "object"}, "sources": {"type": "array"}}},
    },
    {
        "slug": "source_registry_refresh_v1",
        "version": "1",
        "name": "Source Registry Refresh",
        "description": "Refreshes workspace source freshness, confidence and layer registry metadata for executive monitoring.",
        "type": "workflow",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 8_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_refresh", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"workspace_slug": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"source_health": {"type": "object"}, "layers": {"type": "array"}}},
    },
    {
        "slug": "osint_signal_prioritize_v1",
        "version": "1",
        "name": "OSINT Signal Prioritize",
        "description": "Ranks public OSINT, press and rumor signals by geography, institutional impact and decision urgency.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 10_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_signal_batch", "unit_price": 0.04, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"signals": {"type": "array"}, "geography": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"priorities": {"type": "array"}, "geographic_tiers": {"type": "array"}}},
    },
    {
        "slug": "rumor_origin_trace_v1",
        "version": "1",
        "name": "Rumor Origin Trace",
        "description": "Builds an advisory trace of public rumor origin, propagation channels, confidence and recommended response.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 10_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_trace", "unit_price": 0.04, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"rumor_id": {"type": "string"}, "signals": {"type": "array"}}},
        "output_schema": {"type": "object", "properties": {"origin": {"type": "string"}, "spread": {"type": "array"}, "confidence": {"type": "number"}}},
    },
    {
        "slug": "evidence_graph_build_v1",
        "version": "1",
        "name": "Evidence Graph Build",
        "description": "Connects entities, sources, places, projects, events and actions into a workspace-scoped evidence graph.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 10_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_graph", "unit_price": 0.05, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"scope": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"nodes": {"type": "array"}, "edges": {"type": "array"}, "clusters": {"type": "array"}}},
    },
    {
        "slug": "situation_posture_score_v1",
        "version": "1",
        "name": "Situation Posture Score",
        "description": "Scores national posture from territorial, press, agenda, visual, maritime and action-plan signals.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 8_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_score", "unit_price": 0.03, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"signals": {"type": "array"}}},
        "output_schema": {"type": "object", "properties": {"score": {"type": "number"}, "label": {"type": "string"}, "axes": {"type": "array"}}},
    },
    {
        "slug": "maritime_snapshot_read_v1",
        "version": "1",
        "name": "Maritime Snapshot Read",
        "description": "Reads demo-safe or provider-backed port, customs and vessel snapshots for Gulf of Guinea monitoring.",
        "type": "connector",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 8_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_snapshot", "unit_price": 0.03, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"port": {"type": "string"}, "time_range": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"ports": {"type": "array"}, "vessels": {"type": "array"}, "source_health": {"type": "object"}}},
    },
    {
        "slug": "decision_option_rank_v1",
        "version": "1",
        "name": "Decision Option Rank",
        "description": "Ranks advisory options by impact, cost, urgency, confidence and human-validation requirements.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 8_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_decision", "unit_price": 0.03, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"options": {"type": "array"}, "deadline": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"recommended": {"type": "object"}, "alternatives": {"type": "array"}}},
    },
    {
        "slug": "draft_response_email_v1",
        "version": "1",
        "name": "Draft Response Email",
        "description": "Drafts a sourced response email for communication or cabinet teams without sending it automatically.",
        "type": "generation",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 10_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_email_draft", "unit_price": 0.04, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["target_id"], "properties": {"target_id": {"type": "string"}, "recipient": {"type": "string"}, "tone": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"subject": {"type": "string"}, "body": {"type": "string"}, "requires_validation": {"type": "boolean"}}},
    },
    {
        "slug": "visual_source_read_v1",
        "version": "1",
        "name": "Visual Source Read",
        "description": "Reads workspace visual stream sources and their latest capture posture without continuous recording.",
        "type": "connector",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_read", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"source_id": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"sources": {"type": "array"}, "dashboard": {"type": "object"}}},
    },
    {
        "slug": "visual_snapshot_capture_v1",
        "version": "1",
        "name": "Visual Snapshot Capture",
        "description": "Captures one snapshot from an authorized visual source using the configured provider-neutral adapter.",
        "type": "ingestion",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "async", "timeout_ms": 30_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_snapshot", "unit_price": 0.03, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["source_id"], "properties": {"source_id": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"capture": {"type": "object"}, "job": {"type": "object"}}},
    },
    {
        "slug": "visual_snapshot_analyze_v1",
        "version": "1",
        "name": "Visual Snapshot Analyze",
        "description": "Produces a lightweight, non-biometric observation from a visual snapshot.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 15_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_snapshot", "unit_price": 0.04, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["capture_id"], "properties": {"capture_id": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"observation": {"type": "object"}}},
    },
    {
        "slug": "visual_observation_sync_knowledge_v1",
        "version": "1",
        "name": "Visual Observation Sync Knowledge",
        "description": "Synchronizes visual observations into a workspace Knowledge collection for RAG and AYA.",
        "type": "ingestion",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 8_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_observation", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["observation_id"], "properties": {"observation_id": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"collection": {"type": "string"}, "object_key": {"type": "string"}}},
    },
    {
        "slug": "time_context_set_v1",
        "version": "1",
        "name": "Time Context Set",
        "description": "Sets a workspace demo or replay time context for reproducible executive demonstrations.",
        "type": "governance",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": False, "idempotent": False},
        "pricing": {"unit": "per_update", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"current_date": {"type": "string"}, "label": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"demo_time_context": {"type": "object"}}},
    },
    {
        "slug": "territorial_action_window_v1",
        "version": "1",
        "name": "Territorial Action Window",
        "description": "Recommends non-military action windows for a territorial signal using agenda and map context.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_window", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {"zone_id": {"type": "string"}, "target_id": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"recommended_windows": {"type": "array"}}},
    },
    {
        "slug": "sharepoint_ingestion_v1",
        "version": "1",
        "name": "SharePoint Ingestion",
        "description": "Synchronizes a SharePoint library into a knowledge collection.",
        "type": "ingestion",
        "provider": "microsoft",
        "certification_level": "production",
        "execution": {"mode": "async", "timeout_ms": 1_800_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_file", "unit_price": 0.06, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["site_url"], "properties": {
            "site_url": {"type": "string"},
            "library": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "files": {"type": "integer"},
            "skipped": {"type": "integer"},
        }},
    },
    {
        "slug": "voice_transcribe_v1",
        "version": "1",
        "name": "Voice Transcribe",
        "description": "Phase 0 speech-to-text for recorded expert turns, backed by the active VoiceRuntimeProvider.",
        "type": "voice",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 60_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_minute", "unit_price": 0.012, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["audio_ref"], "properties": {
            "audio_ref": {"type": "string"},
            "audio_base64": {"type": "string"},
            "filename": {"type": "string"},
            "content_type": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "transcript": {"type": "string"},
            "model": {"type": "string"},
        }},
    },
    {
        "slug": "voice_tts_v1",
        "version": "1",
        "name": "Voice TTS",
        "description": "Segmented text-to-speech with selectable voices for guided capture sessions.",
        "type": "voice",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "stream", "timeout_ms": 30_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_char", "unit_price": 0.00002, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["text"], "properties": {
            "text": {"type": "string"},
            "voice": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "audio_url": {"type": "string"},
            "audio_base64": {"type": "string"},
            "content_type": {"type": "string"},
            "model": {"type": "string"},
        }},
    },
    {
        "slug": "voice_realtime_session_v1",
        "version": "1",
        "name": "Voice Realtime Session",
        "description": "Starts a provider-neutral realtime voice session with explicit provider, model, transport and fallback policy.",
        "type": "voice",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "stream", "timeout_ms": 30_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_session", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "transport": {"type": "string"},
            "language": {"type": "string"},
            "voice": {"type": "string"},
            "fallback_policy": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "provider": {"type": "string"},
            "transport": {"type": "string"},
            "events": {"type": "array"},
            "capabilities": {"type": "object"},
        }},
    },
    {
        "slug": "voice_realtime_transcribe_v1",
        "version": "1",
        "name": "Voice Realtime Transcribe",
        "description": "Emits text.partial/text.final events from a realtime or cascade transcription provider.",
        "type": "voice",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "stream", "timeout_ms": 60_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_minute", "unit_price": 0.012, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "audio_ref": {"type": "string"},
            "audio_base64": {"type": "string"},
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "language": {"type": "string"},
            "transport": {"type": "string"},
            "fallback_policy": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "transcript": {"type": "string"},
            "text_events": {"type": "array"},
            "provider": {"type": "string"},
            "fallback": {"type": "boolean"},
        }},
    },
    {
        "slug": "voice_realtime_speak_v1",
        "version": "1",
        "name": "Voice Realtime Speak",
        "description": "Produces audio.out events from a realtime, local or cascade speech provider.",
        "type": "voice",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "stream", "timeout_ms": 30_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_char", "unit_price": 0.00002, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["text"], "properties": {
            "text": {"type": "string"},
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "transport": {"type": "string"},
            "language": {"type": "string"},
            "voice": {"type": "string"},
            "fallback_policy": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "audio_base64": {"type": "string"},
            "content_type": {"type": "string"},
            "provider": {"type": "string"},
            "events": {"type": "array"},
        }},
    },
    {
        "slug": "voice_realtime_translate_v1",
        "version": "1",
        "name": "Voice Realtime Translate",
        "description": "Routes live translation events through an OpenAI Realtime or local translation-capable provider.",
        "type": "voice",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "stream", "timeout_ms": 60_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_minute", "unit_price": 0.02, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "text": {"type": "string"},
            "provider": {"type": "string"},
            "source_language": {"type": "string"},
            "target_language": {"type": "string"},
            "transport": {"type": "string"},
            "fallback_policy": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "events": {"type": "array"},
            "translated_text": {"type": "string"},
            "provider": {"type": "string"},
        }},
    },
    {
        "slug": "voice_oracle_turn_v1",
        "version": "1",
        "name": "Voice Oracle Turn",
        "description": "Binds transcript, Knowledge context and evaluator output into the next voice action for a system.",
        "type": "voice",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 15_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_turn", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "answer": {"type": "string"},
            "question": {"type": "object"},
            "gap": {"type": "object"},
            "context": {"type": "object"},
        }},
        "output_schema": {"type": "object", "properties": {
            "action": {"type": "string"},
            "evaluation": {"type": "object"},
            "events": {"type": "array"},
        }},
    },
    {
        "slug": "voice_tandem_oracle_v1",
        "version": "1",
        "name": "Voice Tandem Oracle",
        "description": "Coordinates realtime voice micro-turns with a background Knowledge oracle using provider-neutral latest-wins events.",
        "type": "voice",
        "provider": "internal",
        "certification_level": "beta",
        "execution": {"mode": "stream", "timeout_ms": 15_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_turn", "unit_price": 0.012, "currency": "USD"},
        "input_schema": {"type": "object", "properties": {
            "partial_text": {"type": "string"},
            "final_text": {"type": "string"},
            "turn_id": {"type": "string"},
            "duration_ms": {"type": "integer"},
            "evaluation": {"type": "object"},
            "next_prompt": {"type": "string"},
            "sources": {"type": "array"},
            "provider": {"type": "string"},
            "transport": {"type": "string"},
            "fallback_policy": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "events": {"type": "array"},
            "mode": {"type": "string"},
            "committed": {"type": "boolean"},
        }},
    },
    {
        "slug": "knowledge_gap_analysis_v1",
        "version": "1",
        "name": "Knowledge Gap Analysis",
        "description": "Identifies missing, weakly sourced or tacit knowledge to resolve with an expert.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 15_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.015, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["objective"], "properties": {
            "objective": {"type": "string"},
            "expert_profile": {"type": "string"},
            "context": {"type": "object"},
            "knowledge_refs": {"type": "array"},
        }},
        "output_schema": {"type": "object", "properties": {
            "gaps": {"type": "array"},
        }},
    },
    {
        "slug": "expert_interview_plan_v1",
        "version": "1",
        "name": "Expert Interview Plan",
        "description": "Builds a duration-bounded expert interview agenda from prioritized knowledge gaps.",
        "type": "planning",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 15_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_plan", "unit_price": 0.03, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["objective", "duration_minutes", "gaps"], "properties": {
            "objective": {"type": "string"},
            "expert_profile": {"type": "string"},
            "duration_minutes": {"type": "integer"},
            "gaps": {"type": "array"},
            "context": {"type": "object"},
        }},
        "output_schema": {"type": "object", "properties": {
            "plan": {"type": "object"},
        }},
    },
    {
        "slug": "expert_answer_evaluator_v1",
        "version": "1",
        "name": "Expert Answer Evaluator",
        "description": "Evaluates whether an expert answer is sufficient, partial, contradictory or needs a follow-up.",
        "type": "analysis",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 8_000, "retryable": False, "idempotent": True},
        "pricing": {"unit": "per_answer", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["answer"], "properties": {
            "answer": {"type": "string"},
            "question": {"type": "object"},
            "gap": {"type": "object"},
        }},
        "output_schema": {"type": "object", "properties": {
            "verdict": {"type": "string"},
            "score": {"type": "number"},
            "follow_up": {"type": "string"},
            "signals": {"type": "object"},
        }},
    },
    {
        "slug": "capture_structuring_v1",
        "version": "1",
        "name": "Capture Structuring",
        "description": "Turns transcript and evaluated expert answers into a reviewable knowledge update proposal.",
        "type": "generation",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "sync", "timeout_ms": 20_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_session", "unit_price": 0.04, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["session"], "properties": {
            "session": {"type": "object"},
        }},
        "output_schema": {"type": "object", "properties": {
            "proposal": {"type": "object"},
        }},
    },
    {
        "slug": "audit_log_v1",
        "version": "1",
        "name": "Audit Log",
        "description": "Persists a typed audit event for compliance and replay.",
        "type": "compliance",
        "provider": "internal",
        "certification_level": "enterprise",
        "execution": {"mode": "sync", "timeout_ms": 5_000, "retryable": True, "idempotent": True},
        "pricing": {"unit": "per_call", "unit_price": 0.0001, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["event_type"], "properties": {
            "event_type": {"type": "string"},
            "details": {"type": "object"},
        }},
        "output_schema": {"type": "object", "properties": {
            "id": {"type": "string"},
        }},
    },
    {
        "slug": "ollama_llm_v1",
        "version": "1",
        "name": "Ollama LLM",
        "description": "Generic LLM call routed through the Ollama provider.",
        "type": "llm",
        "provider": "ollama",
        "certification_level": "basic",
        "execution": {"mode": "stream", "timeout_ms": 120_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_1k_tokens", "unit_price": 0.0, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["prompt"], "properties": {
            "prompt": {"type": "string"},
            "model": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "completion": {"type": "string"},
        }},
    },
    {
        "slug": "chain_naive_v1",
        "version": "1",
        "name": "RAG Chain · Naive",
        "description": "Single-pass vector retrieval + LLM answer. Cheapest, fastest, lowest recall.",
        "type": "rag",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "stream", "timeout_ms": 45_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_call", "unit_price": 0.006, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
            "context_id": {"type": "string"},
            **RETRIEVAL_POLICY_PROPERTIES,
        }},
        "output_schema": {"type": "object", "properties": {
            "answer": {"type": "string"},
            "citations": {"type": "array"},
            "decision_steps": {"type": "array"},
        }},
    },
    {
        "slug": "chain_hybrid_v1",
        "version": "1",
        "name": "RAG Chain · Hybrid (HAH)",
        "description": "Two-pass sparse+dense retrieval with RRF fusion before the LLM answer.",
        "type": "rag",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "stream", "timeout_ms": 60_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_call", "unit_price": 0.014, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
            "context_id": {"type": "string"},
            **RETRIEVAL_POLICY_PROPERTIES,
        }},
        "output_schema": {"type": "object", "properties": {
            "answer": {"type": "string"},
            "citations": {"type": "array"},
            "decision_steps": {"type": "array"},
        }},
    },
    {
        "slug": "chain_mixed_hah_v1",
        "version": "1",
        "name": "RAG Chain · Composite HAH (C-HAH)",
        "description": "Budget-aware C-HAH retrieval: runs scoped query variants and fuses via RRF before the LLM answer.",
        "type": "rag",
        "provider": "internal",
        "certification_level": "production",
        "execution": {"mode": "stream", "timeout_ms": 75_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_call", "unit_price": 0.022, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["query"], "properties": {
            "query": {"type": "string"},
            "context_id": {"type": "string"},
            **RETRIEVAL_POLICY_PROPERTIES,
        }},
        "output_schema": {"type": "object", "properties": {
            "answer": {"type": "string"},
            "citations": {"type": "array"},
            "decision_steps": {"type": "array"},
        }},
    },
    {
        "slug": "azure_llm_v1",
        "version": "1",
        "name": "Azure OpenAI LLM",
        "description": "LLM call routed through Azure OpenAI.",
        "type": "llm",
        "provider": "azure",
        "certification_level": "production",
        "execution": {"mode": "stream", "timeout_ms": 60_000, "retryable": True, "idempotent": False},
        "pricing": {"unit": "per_1k_tokens", "unit_price": 0.01, "currency": "USD"},
        "input_schema": {"type": "object", "required": ["prompt"], "properties": {
            "prompt": {"type": "string"},
            "model": {"type": "string"},
        }},
        "output_schema": {"type": "object", "properties": {
            "completion": {"type": "string"},
        }},
    },
]


# ---- Universal Capabilities -------------------------------------------------
SEED_CAPABILITIES: List[Dict[str, Any]] = [
    {
        "slug": "workspace_assistant",
        "name": "Workspace Assistant",
        "tier": "universal",
        "description": "Always-on workspace chat system for sourced answers, fast retrieval, Deep Search escalation, actions and audit trails.",
        "input_unit": "chat_turn",
        "output_unit": "sourced_answer",
        "skill_slugs": [
            "chat_trivial_bypass_v1",
            "chat_action_resolver_v1",
            "chat_grounding_policy_v1",
            "chat_agentic_plan_v1",
            "chat_self_correct_v1",
            "llm_rag_answer_v1",
            "semantic_search_v1",
            "multi_hop_retrieve_v1",
            "chain_mixed_hah_v1",
            "eval_radar_v1",
            "claim_audit_v1",
            "response_eval_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_outcome", "unit_price": 0.06, "currency": "USD"},
        "value_per_outcome": 1.50,
        "confidence_threshold": 0.65,
        "sla": {"max_latency_ms": 8000, "fast_answer_target_ms": 4500},
        "roi_model": {"type": "time_saved_plus_decision_quality"},
    },
    {
        "slug": "intelligent_qa",
        "name": "Intelligent Q&A",
        "tier": "universal",
        "description": "Answers questions over your knowledge base with citations and a verifiable reasoning trail.",
        "input_unit": "question",
        "output_unit": "answer",
        "skill_slugs": ["llm_rag_answer_v1", "semantic_search_v1", "claim_audit_v1", "audit_log_v1"],
        "pricing": {"unit": "per_outcome", "unit_price": 0.05, "currency": "USD"},
        "value_per_outcome": 1.20,
        "confidence_threshold": 0.65,
        "sla": {"max_latency_ms": 8000, "uptime": 0.995},
        "roi_model": {"type": "value_minus_cost"},
    },
    {
        "slug": "knowledge_curation",
        "name": "Knowledge Curation",
        "tier": "universal",
        "description": "Continuously ingests, deduplicates and indexes documents from any source (uploads, SharePoint, web feeds).",
        "input_unit": "document",
        "output_unit": "indexed_chunk",
        "skill_slugs": ["document_ingestion_v1", "sharepoint_ingestion_v1", "intelligence_batch_v1"],
        "pricing": {"unit": "per_doc", "unit_price": 0.05, "currency": "USD"},
        "value_per_outcome": 0.40,
        "confidence_threshold": None,
        "sla": {"freshness_minutes": 60},
        "roi_model": {"type": "time_saved"},
    },
    {
        "slug": "voice2voice_interaction",
        "name": "Voice2Voice Interaction",
        "tier": "universal",
        "description": "Provider-neutral realtime voice loop for chat, capture and custom systems, with cascade fallback and auditable events.",
        "input_unit": "voice_session",
        "output_unit": "conversation_turn",
        "skill_slugs": [
            "voice_realtime_session_v1",
            "voice_realtime_transcribe_v1",
            "voice_oracle_turn_v1",
            "voice_tandem_oracle_v1",
            "voice_realtime_speak_v1",
            "voice_realtime_translate_v1",
            "voice_transcribe_v1",
            "voice_tts_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_session", "unit_price": 0.12, "currency": "USD"},
        "value_per_outcome": 0.90,
        "confidence_threshold": 0.70,
        "sla": {"max_latency_ms": 4000},
        "roi_model": {"type": "value_minus_cost"},
    },
    {
        "slug": "voice_assistant",
        "name": "Voice Assistant",
        "tier": "universal",
        "description": "Transcribe a question, retrieve an answer, speak it back. End-to-end voice loop.",
        "input_unit": "audio_minute",
        "output_unit": "answer",
        "skill_slugs": [
            "voice_realtime_session_v1",
            "voice_realtime_transcribe_v1",
            "voice_tandem_oracle_v1",
            "llm_rag_answer_v1",
            "voice_realtime_speak_v1",
            "voice_transcribe_v1",
            "voice_tts_v1",
        ],
        "pricing": {"unit": "per_outcome", "unit_price": 0.10, "currency": "USD"},
        "value_per_outcome": 0.60,
        "confidence_threshold": 0.70,
        "sla": {"max_latency_ms": 4000},
        "roi_model": {"type": "value_minus_cost"},
    },
    {
        "slug": "expert_knowledge_capture",
        "name": "Expert Knowledge Capture",
        "tier": "universal",
        "description": "Prepares and runs guided expert interviews that resolve knowledge gaps and produce reviewable knowledge-base updates.",
        "input_unit": "capture_session",
        "output_unit": "knowledge_update_proposal",
        "skill_slugs": [
            "knowledge_gap_analysis_v1",
            "expert_interview_plan_v1",
            "voice_realtime_session_v1",
            "voice_realtime_transcribe_v1",
            "semantic_search_v1",
            "expert_answer_evaluator_v1",
            "voice_oracle_turn_v1",
            "voice_tandem_oracle_v1",
            "capture_structuring_v1",
            "voice_realtime_speak_v1",
            "voice_transcribe_v1",
            "voice_tts_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_session", "unit_price": 0.35, "currency": "USD"},
        "value_per_outcome": 8.00,
        "confidence_threshold": 0.70,
        "sla": {"target_duration_minutes": 20, "max_plan_latency_ms": 15000},
        "roi_model": {"type": "time_saved_plus_knowledge_retention"},
    },
    {
        "slug": "sovereign_translation_suite",
        "name": "Sovereign Translation Suite",
        "tier": "industry",
        "industry": "regulated_translation",
        "description": "Runs DITA translation batches with local model routing, agent QA, deterministic guardrails, replay and audit-ready delivery.",
        "input_unit": "dita_batch",
        "output_unit": "accepted_delivery",
        "skill_slugs": [
            "translation_archive_ingest_v1",
            "translation_memory_retrieve_v1",
            "translation_label_index_resolve_v1",
            "translation_pivot_normalize_v1",
            "translation_fanout_v1",
            "translation_j2450_qa_v1",
            "translation_post_guard_v1",
            "translation_cdt_gate_v1",
            "translation_package_delivery_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_1000_source_words", "unit_price": 0.82, "currency": "EUR"},
        "value_per_outcome": 4_800.00,
        "confidence_threshold": 0.94,
        "sla": {"availability": "99.95%", "batch_completion_target_hours": 36, "max_replay_sla_hours": 4},
        "roi_model": {"type": "lsp_cost_avoidance_plus_cycle_time"},
    },
    {
        "slug": "answer_quality_audit",
        "name": "Answer Quality Audit",
        "tier": "universal",
        "description": "Continuously evaluates answer quality (groundedness, relevance, safety) and alerts on regressions.",
        "input_unit": "answer",
        "output_unit": "evaluation",
        "skill_slugs": ["eval_radar_v1", "claim_audit_v1"],
        "pricing": {"unit": "per_outcome", "unit_price": 0.04, "currency": "USD"},
        "value_per_outcome": 0.20,
        "confidence_threshold": None,
        "sla": {},
        "roi_model": {"type": "risk_avoided"},
    },
    {
        "slug": "market_signal_brief",
        "name": "Market Signal Brief",
        "tier": "industry",
        "industry": "finance",
        "description": "Aggregates intelligence feeds into a periodic decision-grade brief with semantic targets.",
        "input_unit": "feed_batch",
        "output_unit": "brief",
        "skill_slugs": ["intelligence_batch_v1", "llm_rag_answer_v1", "audit_log_v1"],
        "pricing": {"unit": "per_brief", "unit_price": 1.20, "currency": "USD"},
        "value_per_outcome": 8.00,
        "confidence_threshold": 0.65,
        "sla": {"freshness_minutes": 240},
        "roi_model": {"type": "value_minus_cost"},
    },
    {
        "slug": "government_mission_room",
        "name": "Government Mission Room",
        "tier": "industry",
        "industry": "government",
        "description": "Executive sovereign cockpit combining briefing, open intelligence, projects, territorial map, assistant and advisory action drafts.",
        "input_unit": "ministerial_signal",
        "output_unit": "advisory_decision_pack",
        "skill_slugs": [
            "ministerial_briefing_v1",
            "news_signal_synthesis_v1",
            "project_risk_explainer_v1",
            "territorial_signal_map_v1",
            "instruction_draft_v1",
            "scenario_generate_v1",
            "scenario_compare_v1",
            "scenario_recommend_v1",
            "map_layer_read_v1",
            "map_zone_score_v1",
            "map_signal_attach_v1",
            "map_recommendation_generate_v1",
            "visual_source_read_v1",
            "visual_snapshot_capture_v1",
            "visual_snapshot_analyze_v1",
            "visual_observation_sync_knowledge_v1",
            "calendar_read_v1",
            "calendar_create_event_v1",
            "calendar_update_event_v1",
            "calendar_cancel_event_v1",
            "calendar_daily_summary_v1",
            "action_plan_create_v1",
            "action_plan_reschedule_v1",
            "action_plan_status_v1",
            "action_plan_cancel_v1",
            "time_context_set_v1",
            "territorial_action_window_v1",
            "source_registry_refresh_v1",
            "osint_signal_prioritize_v1",
            "rumor_origin_trace_v1",
            "evidence_graph_build_v1",
            "situation_posture_score_v1",
            "maritime_snapshot_read_v1",
            "decision_option_rank_v1",
            "draft_response_email_v1",
            "llm_rag_answer_v1",
            "chain_mixed_hah_v1",
            "voice_tandem_oracle_v1",
            "voice_realtime_session_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_daily_room", "unit_price": 2.80, "currency": "USD"},
        "value_per_outcome": 20.00,
        "confidence_threshold": 0.72,
        "sla": {"freshness_minutes": 60, "max_latency_ms": 10000},
        "roi_model": {"type": "decision_latency_reduced"},
    },
    {
        "slug": "ministerial_daily_briefing",
        "name": "Ministerial Daily Briefing",
        "tier": "industry",
        "industry": "government",
        "description": "Produces a daily ministerial brief with agenda, priorities, risks, decisions expected and talking points.",
        "input_unit": "workspace_day",
        "output_unit": "briefing",
        "skill_slugs": ["ministerial_briefing_v1", "calendar_daily_summary_v1", "action_plan_status_v1", "llm_rag_answer_v1", "audit_log_v1"],
        "pricing": {"unit": "per_brief", "unit_price": 0.35, "currency": "USD"},
        "value_per_outcome": 8.00,
        "confidence_threshold": 0.72,
        "sla": {"max_latency_ms": 12000},
        "roi_model": {"type": "time_saved"},
    },
    {
        "slug": "open_intelligence_watch",
        "name": "Open Intelligence Watch",
        "tier": "industry",
        "industry": "government",
        "description": "Monitors RSS/open sources and converts weak signals into sourced risk summaries.",
        "input_unit": "feed_batch",
        "output_unit": "signal_brief",
        "skill_slugs": [
            "intelligence_batch_v1",
            "news_signal_synthesis_v1",
            "source_registry_refresh_v1",
            "osint_signal_prioritize_v1",
            "rumor_origin_trace_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_batch", "unit_price": 0.80, "currency": "USD"},
        "value_per_outcome": 6.00,
        "confidence_threshold": 0.65,
        "sla": {"freshness_minutes": 60},
        "roi_model": {"type": "risk_avoided"},
    },
    {
        "slug": "scenario_fusion_monitor",
        "name": "Scenario Fusion Monitor",
        "tier": "industry",
        "industry": "government",
        "description": "Fuses map, news, visual, calendar and action-plan signals into a government mission-control scenario.",
        "input_unit": "cross_source_signal",
        "output_unit": "strategic_posture",
        "skill_slugs": [
            "news_signal_synthesis_v1",
            "territorial_signal_map_v1",
            "map_layer_read_v1",
            "map_zone_score_v1",
            "visual_source_read_v1",
            "visual_snapshot_analyze_v1",
            "calendar_daily_summary_v1",
            "action_plan_status_v1",
            "scenario_generate_v1",
            "scenario_compare_v1",
            "scenario_recommend_v1",
            "chain_mixed_hah_v1",
            "voice_tandem_oracle_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_scenario_cycle", "unit_price": 0.95, "currency": "USD"},
        "value_per_outcome": 12.00,
        "confidence_threshold": 0.70,
        "sla": {"freshness_minutes": 30, "max_latency_ms": 10000},
        "roi_model": {"type": "decision_latency_reduced"},
    },
    {
        "slug": "strategic_project_pilotage",
        "name": "Strategic Project Pilotage",
        "tier": "industry",
        "industry": "government",
        "description": "Explains strategic project health, delay causes, risks and advisory options under human control.",
        "input_unit": "project",
        "output_unit": "risk_explanation",
        "skill_slugs": ["project_risk_explainer_v1", "scenario_generate_v1", "scenario_compare_v1", "scenario_recommend_v1", "semantic_search_v1", "instruction_draft_v1", "action_plan_create_v1", "action_plan_status_v1", "audit_log_v1"],
        "pricing": {"unit": "per_project_review", "unit_price": 0.45, "currency": "USD"},
        "value_per_outcome": 7.00,
        "confidence_threshold": 0.70,
        "sla": {"max_latency_ms": 10000},
        "roi_model": {"type": "decision_quality"},
    },
    {
        "slug": "territorial_action_map",
        "name": "Territorial Action Map",
        "tier": "industry",
        "industry": "government",
        "description": "Transforms territorial signals and RAG outputs into an illustrative executive map for non-military preventive action.",
        "input_unit": "territorial_signal",
        "output_unit": "map_zone",
        "skill_slugs": [
            "territorial_signal_map_v1",
            "territorial_action_window_v1",
            "map_layer_read_v1",
            "map_zone_score_v1",
            "map_signal_attach_v1",
            "map_recommendation_generate_v1",
            "map_command_apply_v1",
            "situation_posture_score_v1",
            "maritime_snapshot_read_v1",
            "chain_mixed_hah_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_map", "unit_price": 0.50, "currency": "USD"},
        "value_per_outcome": 7.50,
        "confidence_threshold": 0.68,
        "sla": {"max_latency_ms": 10000},
        "roi_model": {"type": "situational_awareness"},
    },
    {
        "slug": "visual_situation_watch",
        "name": "Live Visual Monitor",
        "tier": "industry",
        "industry": "government",
        "description": "Displays authorized live visual sources, captures snapshots, creates non-biometric observations and syncs them to Knowledge.",
        "input_unit": "visual_source",
        "output_unit": "visual_observation",
        "skill_slugs": ["visual_source_read_v1", "visual_snapshot_capture_v1", "visual_snapshot_analyze_v1", "visual_observation_sync_knowledge_v1", "chain_mixed_hah_v1", "audit_log_v1"],
        "pricing": {"unit": "per_source_day", "unit_price": 0.45, "currency": "USD"},
        "value_per_outcome": 6.50,
        "confidence_threshold": 0.62,
        "sla": {"freshness_minutes": 60, "max_capture_latency_ms": 30000},
        "roi_model": {"type": "situational_awareness"},
    },
    {
        "slug": "government_calendar_assist",
        "name": "Government Calendar Assist",
        "tier": "industry",
        "industry": "government",
        "description": "Reads institutional agenda constraints and recommends decision windows for government operations.",
        "input_unit": "workspace_day",
        "output_unit": "agenda_arbitrage",
        "skill_slugs": [
            "calendar_read_v1",
            "calendar_create_event_v1",
            "calendar_update_event_v1",
            "calendar_cancel_event_v1",
            "calendar_daily_summary_v1",
            "action_plan_status_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_day", "unit_price": 0.25, "currency": "USD"},
        "value_per_outcome": 5.00,
        "confidence_threshold": 0.70,
        "sla": {"freshness_minutes": 15, "max_latency_ms": 8000},
        "roi_model": {"type": "time_saved"},
    },
    {
        "slug": "aya_voice_command",
        "name": "AYA Voice Command",
        "tier": "industry",
        "industry": "government",
        "description": "Voice-first command layer for AYA to brief, focus map/webcam panels and prepare advisory actions.",
        "input_unit": "voice_turn",
        "output_unit": "mission_command",
        "skill_slugs": ["voice_tandem_oracle_v1", "voice_realtime_session_v1", "llm_rag_answer_v1", "audit_log_v1"],
        "pricing": {"unit": "per_voice_session", "unit_price": 0.18, "currency": "USD"},
        "value_per_outcome": 5.50,
        "confidence_threshold": 0.68,
        "sla": {"max_latency_ms": 5000},
        "roi_model": {"type": "time_saved"},
    },
    {
        "slug": "executive_instruction_drafting",
        "name": "Executive Instruction Drafting",
        "tier": "industry",
        "industry": "government",
        "description": "Drafts sourced cabinet instructions that remain advisory and require human validation before any external action.",
        "input_unit": "decision_signal",
        "output_unit": "draft_instruction",
        "skill_slugs": ["instruction_draft_v1", "draft_response_email_v1", "decision_option_rank_v1", "claim_audit_v1", "audit_log_v1"],
        "pricing": {"unit": "per_draft", "unit_price": 0.25, "currency": "USD"},
        "value_per_outcome": 4.50,
        "confidence_threshold": 0.75,
        "sla": {"max_latency_ms": 10000},
        "roi_model": {"type": "time_saved"},
    },
    {
        "slug": "osint_rumor_intelligence",
        "name": "OSINT & Rumor Intelligence",
        "tier": "industry",
        "industry": "government",
        "description": "Prioritizes public press and demo-safe rumor signals by geography, origin, institutional impact and response urgency.",
        "input_unit": "osint_signal",
        "output_unit": "prioritized_signal",
        "skill_slugs": [
            "intelligence_batch_v1",
            "source_registry_refresh_v1",
            "osint_signal_prioritize_v1",
            "rumor_origin_trace_v1",
            "news_signal_synthesis_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_signal_cycle", "unit_price": 0.55, "currency": "USD"},
        "value_per_outcome": 9.00,
        "confidence_threshold": 0.68,
        "sla": {"freshness_minutes": 60},
        "roi_model": {"type": "risk_avoided"},
    },
    {
        "slug": "evidence_graph",
        "name": "Evidence Graph",
        "tier": "industry",
        "industry": "government",
        "description": "Connects sources, entities, places, projects, rumors, agenda constraints and advisory actions for explainable AYA answers.",
        "input_unit": "evidence_record",
        "output_unit": "evidence_graph",
        "skill_slugs": [
            "evidence_graph_build_v1",
            "semantic_search_v1",
            "chain_mixed_hah_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_graph_refresh", "unit_price": 0.30, "currency": "USD"},
        "value_per_outcome": 7.50,
        "confidence_threshold": 0.70,
        "sla": {"freshness_minutes": 120},
        "roi_model": {"type": "explainability"},
    },
    {
        "slug": "maritime_customs_watch",
        "name": "Maritime & Customs Watch",
        "tier": "industry",
        "industry": "government",
        "description": "Monitors ports, customs context and Gulf of Guinea maritime snapshots for economic and infrastructure risk briefings.",
        "input_unit": "port_signal",
        "output_unit": "maritime_posture",
        "skill_slugs": [
            "maritime_snapshot_read_v1",
            "map_layer_read_v1",
            "osint_signal_prioritize_v1",
            "situation_posture_score_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_snapshot", "unit_price": 0.25, "currency": "USD"},
        "value_per_outcome": 6.50,
        "confidence_threshold": 0.62,
        "sla": {"freshness_minutes": 120},
        "roi_model": {"type": "situational_awareness"},
    },
    {
        "slug": "strategic_forecasts",
        "name": "Strategic Forecasts",
        "tier": "industry",
        "industry": "government",
        "description": "Turns fused signals into short-horizon forecast options with impact, cost, confidence and decision windows.",
        "input_unit": "cross_source_signal",
        "output_unit": "forecast_option",
        "skill_slugs": [
            "situation_posture_score_v1",
            "scenario_generate_v1",
            "scenario_compare_v1",
            "scenario_recommend_v1",
            "decision_option_rank_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_forecast_cycle", "unit_price": 0.45, "currency": "USD"},
        "value_per_outcome": 10.00,
        "confidence_threshold": 0.70,
        "sla": {"freshness_minutes": 60},
        "roi_model": {"type": "decision_latency_reduced"},
    },
    {
        "slug": "decision_desk",
        "name": "Decision Desk",
        "tier": "industry",
        "industry": "government",
        "description": "Ranks advisory options and drafts cabinet or communication responses under human validation.",
        "input_unit": "decision_signal",
        "output_unit": "validated_draft",
        "skill_slugs": [
            "decision_option_rank_v1",
            "draft_response_email_v1",
            "instruction_draft_v1",
            "action_plan_create_v1",
            "action_plan_status_v1",
            "audit_log_v1",
        ],
        "pricing": {"unit": "per_decision_pack", "unit_price": 0.35, "currency": "USD"},
        "value_per_outcome": 8.50,
        "confidence_threshold": 0.75,
        "sla": {"max_latency_ms": 10000},
        "roi_model": {"type": "time_saved"},
    },
    {
        "slug": "compliance_assistant",
        "name": "Compliance Assistant",
        "tier": "industry",
        "industry": "legal",
        "description": "Answers compliance questions with full citation, audit log and HITL escalation when confidence is low.",
        "input_unit": "question",
        "output_unit": "answer",
        "skill_slugs": ["llm_rag_answer_v1", "claim_audit_v1", "audit_log_v1"],
        "pricing": {"unit": "per_outcome", "unit_price": 0.20, "currency": "USD"},
        "value_per_outcome": 4.00,
        "confidence_threshold": 0.80,
        "sla": {"max_latency_ms": 10_000, "uptime": 0.999},
        "roi_model": {"type": "value_minus_cost"},
    },
]


def seed_skills_and_capabilities(db: DBSession) -> Dict[str, int]:
    """Idempotent upsert of the seed registry. Safe to call on every boot.

    Returns a small report so the startup log can show what changed.
    """
    now = datetime.utcnow()
    skills_added = 0
    skills_updated = 0
    skill_id_by_slug: Dict[str, str] = {}

    # Skills first.
    for entry in SEED_SKILLS:
        existing = db.query(Skill).filter(Skill.slug == entry["slug"]).first()
        if existing:
            for key in ("name", "description", "type", "provider", "certification_level",
                        "execution", "pricing", "input_schema", "output_schema", "version"):
                if entry.get(key) is not None:
                    setattr(existing, key, entry[key])
            existing.is_seeded = "Y"
            existing.updated_at = now
            skill_id_by_slug[existing.slug] = existing.id
            skills_updated += 1
        else:
            sk = Skill(
                slug=entry["slug"],
                version=entry["version"],
                name=entry["name"],
                description=entry["description"],
                type=entry["type"],
                provider=entry["provider"],
                certification_level=entry["certification_level"],
                execution=entry["execution"],
                pricing=entry["pricing"],
                input_schema=entry["input_schema"],
                output_schema=entry["output_schema"],
                is_seeded="Y",
                workspace_id=None,
            )
            db.add(sk)
            db.flush()
            skill_id_by_slug[sk.slug] = sk.id
            skills_added += 1

    # Capabilities reference skill ids.
    caps_added = 0
    caps_updated = 0
    for entry in SEED_CAPABILITIES:
        skill_ids = [skill_id_by_slug[s] for s in entry["skill_slugs"] if s in skill_id_by_slug]
        existing = db.query(Capability).filter(Capability.slug == entry["slug"]).first()
        if existing:
            for key in ("name", "description", "tier", "industry", "input_unit", "output_unit",
                        "pricing", "value_per_outcome", "confidence_threshold", "sla", "roi_model"):
                if entry.get(key) is not None:
                    setattr(existing, key, entry[key])
            existing.skill_ids = skill_ids
            existing.is_seeded = "Y"
            existing.updated_at = now
            caps_updated += 1
        else:
            cap = Capability(
                slug=entry["slug"],
                name=entry["name"],
                description=entry["description"],
                tier=entry["tier"],
                industry=entry.get("industry"),
                input_unit=entry["input_unit"],
                output_unit=entry["output_unit"],
                skill_ids=skill_ids,
                pricing=entry["pricing"],
                value_per_outcome=entry["value_per_outcome"],
                confidence_threshold=entry["confidence_threshold"],
                sla=entry["sla"],
                roi_model=entry["roi_model"],
                is_seeded="Y",
                workspace_id=None,
            )
            db.add(cap)
            caps_added += 1

    db.commit()
    return {
        "skills_added": skills_added,
        "skills_updated": skills_updated,
        "capabilities_added": caps_added,
        "capabilities_updated": caps_updated,
    }
