"""Add app_settings table

Revision ID: 70e2ecf77346
Revises: 539cd1844ec6
Create Date: 2025-12-11 08:31:23.480852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e2ecf77346'
down_revision = '539cd1844ec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('default_model', sa.String(), nullable=True),
    sa.Column('default_provider', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('preferred_agents', sa.JSON(), nullable=True),
    sa.Column('enable_rag', sa.Boolean(), nullable=True),
    sa.Column('enable_reasoning', sa.Boolean(), nullable=True),
    sa.Column('enable_search', sa.Boolean(), nullable=True),
    sa.Column('rag_top_k', sa.Integer(), nullable=True),
    sa.Column('rag_similarity_threshold', sa.Float(), nullable=True),
    sa.Column('enable_streaming', sa.Boolean(), nullable=True),
    sa.Column('streaming_speed', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('font_size', sa.String(), nullable=True),
    sa.Column('show_reasoning_traces', sa.Boolean(), nullable=True),
    sa.Column('show_sources', sa.Boolean(), nullable=True),
    sa.Column('auto_expand_reasoning', sa.Boolean(), nullable=True),
    sa.Column('api_timeout', sa.Integer(), nullable=True),
    sa.Column('enable_caching', sa.Boolean(), nullable=True),
    sa.Column('cache_ttl', sa.Integer(), nullable=True),
    sa.Column('enable_rate_limiting', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('ollama_base_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###

