#!/usr/bin/env bash
# Build the three Agentium images, push by digest, write values-ci-images.yaml.
# Not a release GO. Images stay off :local.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
REGISTRY="${AGENTIUM_LAB_REGISTRY:?AGENTIUM_LAB_REGISTRY is required}"
SHA="${CI_COMMIT_SHA:-$(git -C "$ROOT" rev-parse HEAD)}"
OUT="${AGENTIUM_CI_IMAGES_FILE:-$ROOT/ops/helm/agentium/values-ci-images.yaml}"
PIP_INDEX_URL="${PIP_INDEX_URL:-}"

REGISTRY="${REGISTRY%/}"

digest_of() {
  local ref="$1"
  local digest
  digest="$(docker image inspect --format '{{index .RepoDigests 0}}' "$ref")"
  if [[ -z "$digest" || "$digest" != *@sha256:* ]]; then
    printf 'no digest for %s\n' "$ref" >&2
    exit 1
  fi
  printf '%s\n' "$digest"
}

build_push() {
  local component="$1"
  local dockerfile="$2"
  local tag="${REGISTRY}/agentium-${component}:${SHA}"
  local extra=()
  extra+=(--build-arg "AGENTIUM_IMAGE_REVISION=${SHA}")
  if [[ "$component" != "frontend" ]]; then
    : "${PIP_INDEX_URL:?PIP_INDEX_URL is required for ${component}}"
    extra+=(--build-arg "PIP_INDEX_URL=${PIP_INDEX_URL}")
  fi
  docker build "${extra[@]}" -f "$ROOT/$dockerfile" -t "$tag" "$ROOT" >&2
  docker push "$tag" >&2
  digest_of "$tag"
}

FRONTEND_REF="$(build_push frontend docker/Dockerfile.agentium-frontend)"
BACKEND_REF="$(build_push backend docker/Dockerfile.agentium-backend)"
WORKER_REF="$(build_push worker docker/Dockerfile.agentium-worker)"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# Generated by ops/scripts/build-lab-images.sh — do not commit.
image:
  pullPolicy: IfNotPresent
  frontend: ${FRONTEND_REF}
  backend: ${BACKEND_REF}
  worker: ${WORKER_REF}
EOF

printf 'wrote %s\n' "$OUT" >&2
printf 'frontend %s\nbackend %s\nworker %s\n' "$FRONTEND_REF" "$BACKEND_REF" "$WORKER_REF" >&2
